### ISSUE TITLE
Commonalities release 0.3.0

### ISSUE THREAD

**Issue by rartych** [camaraproject/Commonalities#111]
**Problem description**
Release 0.2.0 has been published. New topics are being discussed: security scheme, linting rules, test definitions and other changes and clarifications in API Design Guidelines.

**Expected action**
Agree with TSC on Commonalities release schedule.

Define PRs and Issues that should be closed before the next release.

**Additional context**
This release can be considered as a base for common release of CAMARA subprojects.

**Comment by jordonezlucena** [comment]
What is the deadline to complete expected actions? 
For the agreement by TSC, we may need to include an agenda point in one of the upcoming TSC meetings, and circulate send out the material beforehand (7 days in advance), so TSC delegates have the background.
For the PR and issues, do you a first list?

**Comment by rartych** [comment]
The topics that need to be included in the release as discussed during last meeting:

- Linting ruleset
   - Issue https://github.com/camaraproject/Commonalities/issues/15
   - PRs  https://github.com/camaraproject/Commonalities/pull/74 https://github.com/camaraproject/Commonalities/pull/110
- Security schemes and scopes - depends on decisions in Identity&Consent Subproject
   - PR [https://github.com/camaraproject/Commonalities/pull/57 to be reviewed and focused on scope naming guidelines
- Test definitions guidelines
    - Issue https://github.com/camaraproject/Commonalities/issues/94
 - Response filtering updates
    - Issues https://github.com/camaraproject/Commonalities/issues/97, https://github.com/camaraproject/Commonalities/issues/98 https://github.com/camaraproject/Commonalities/issues/99
     - Issue https://github.com/camaraproject/Commonalities/issues/103

Target date for release 0.3.0: to be ready for approval on 05.02.2024
