### ISSUE TITLE
Glossary update

### ISSUE THREAD

**Issue by ECORMAC** [camaraproject/Commonalities#114]
**Problem description**
In the number verifiication group (i.e. in the Yaml) certain terms are being used but not in a consistent fashion, for example "service provider", it is not clear if this refers to the CSP / MNO providing the service or to an ASP (application service provider) providing the service to their end-users.

**Expected action**
Glossary should be updated with the following terms: "application provider", "application service provider", "communication service provider / MNO"

**Additional context**

**Comment by rartych** [comment]
No further activity
