### ISSUE TITLE
Explicitly state how to identify "API Name"

### ISSUE THREAD

**Issue by gmuratk** [camaraproject/Commonalities#122]
**Problem description**
Both Design Guidelines and ICM-Access and User Consent documents have statements for use of 'API Name'.  However, in design guidelines, there is no explicit reference or statement that clarify for the implementors from where to get it or how derive it.

**Expected action**
Given the dependency to correctness of the API name in formulation of other strings as attribute values (e.g. scopes, event-type - see below), documentation should have explicit definition of the API name.

**Additional context**
Some of the references to API Name
https://github.com/camaraproject/IdentityAndConsentManagement/blob/main/documentation/CAMARA-API-access-and-user-consent.md#purpose-definition

https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#102-security-implementation
https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#12-subscription-notification--event

Relevant issues to note:
Following 2 issues suggest removal of basePath variable and put the value as fixed into the "servers" object "url" property.  Just pointing as some possibile solutions may suggest use of basePath variable that exist in some of the APIs.
https://github.com/camaraproject/QualityOnDemand/issues/251
https://github.com/camaraproject/ReleaseManagement/issues/17

**Comment by rartych** [comment]
PR #57 defines: 

> api-name is the API name specified as the base path, prior to the API version, in the servers[*].url property

**Comment by rartych** [comment]
Looks it is resolved
