### ISSUE TITLE
API Design - Error Handling should include RFC6749 exception

### ISSUE THREAD

**Issue by laughingbiscuit** [camaraproject/Commonalities#129]
**Problem description**

The [API Design Guidelines](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#6-error-responses) discuss the standardized error format. 

```
{
   "status": 400,
   "code": "INVALID_ARGUMENT",
   "message": "A human readable description of what the event represent"
}
```

This makes sense for most APIs, except existing OAuth APIs such as when obtaining client_credentials access token. There are already errors defined for this in the format [here](https://datatracker.ietf.org/doc/html/rfc6749#appendix-A.7):

```
{
  "error":"xxx",
  "error_description": "xxx",
  "error_uri": "xxx"
}

```

**Expected action**

Documentation should indicate which format takes priority.

**Comment by eric-murray** [comment]
The API design guidelines only apply to the service APIs. The standards and profiles that apply to the authentication flow itself are being discussed within the Identity & Consent working group. The already standardised error response will apply unless changes are agreed by that working group.

**Comment by rartych** [comment]
@jpengar Could you get some insights/views from Identity & Consent subproject how to resolve this issue? More specific problem is also presented also in #128.

**Comment by AxelNennker** [comment]
@rartych As per your request I commented on the original issue https://github.com/camaraproject/Commonalities/issues/128#issuecomment-1942012539

**Comment by jpengar** [comment]
I agree with Axel. 
On the one hand we have the AuthZ/AuthN process to get an access_token to access CAMARA Service APIs. The authorization flows agreed in CAMARA follow the OpenID connect/OAuth standards. So the error format will be the one defined by those standards for the Authorize Request and the Token Request. 
On the other hand, we have CAMARA NBI interface to consume Service APIs, i.e. API client uses obtained access_token to consume the target CAMARA API for which the access_token was obtained. The API design guidelines, and especially in this case the defined error format, only apply to the invocation of service APIs.
