### ISSUE TITLE
Ambiguity in Guidelines regarding scope syntax

### ISSUE THREAD

**Issue by Kevsy** [camaraproject/Commonalities#135]
**Problem description**
Line 931 and 932 of Design Guidelines define `scope` syntax as follows:

- (931) **Use the kebab-case nomenclature** to define API names, resources, and scope permissions.
- (932) **Recommended Format**: `<API_name>-<Resource>-<Permission>`

Line 931 "kebab-case" implies lower kebab-case (also used in the image example following)
Line 932 implies Upper Snake case for API_name followed by Upper Kebab-case

**Expected behavior**
Line 932 to say:

**Recommended Format**: `<api-name>-<resource>-<permission>`

**Comment by Kevsy** [comment]
Fixed in #136

**Comment by rartych** [comment]
Closing as https://github.com/camaraproject/Commonalities/pull/136 is closed, and resolved within #57
