### ISSUE TITLE
Explictly indicate in guideline that datetime use UTC

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/Commonalities#14]
Got a question from an implementation in progress so probably worth to set once: 

Could we "decide" that date-time attribute use UTC (and should be indicated in the attribute description) - except if another rule is explicitly stated in an attribute description. 

This is probably something to be added in the CAMARA_Common.json ?

**Comment by eric-murray** [comment]
I'm going to restate my original position, which is that we should adopt RFC 3339 with the following two additional requirements on API consumers:
- Any underscores `_` and spaces should be replaced by a capital `T`
- Any lower cases letters (only possibilities should be `t` or `z`) should be replaced by the upper case equivalent

Neither of these rules would appear to be a particularly onerous requirement.

**Comment by rartych** [comment]
It looks that we agree on using timestamp format according to [RFC3339]( https://datatracker.ietf.org/doc/html/rfc3339).
@bigludo7 Could you prepare relevant PR?

BTW, the same format is used in [cloudevents specification ](https://github.com/cloudevents/spec/blob/v1.0/spec.md#time).

**Comment by bigludo7** [comment]
@rartych 
Yes.
I'm not sure which document update - We do not have this level of information in Design Guideline document so I'm hesitating to update Commonalities/artifacts/CAMARA_common.json file or to add this information in the Glossary.md file. 
WDYT ?

**Comment by PedroDiez** [comment]
Some suggestion: 

maybe provide some input for "date" fields within section
https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#115-data-definitions

to indicate that within its description it MUST be included:
"It must follow RFC 3339 and must have time zone. Recommended format is yyyy-MM-dd'T'HH:mm:ss.SSSZ (i.e. which allows 2023-07-03T14:27:08.312+02:00 or 2023-07-03T12:27:08.312Z)"

Therefore besides the specific meaning of the "date" field, we all can use a common sentence to refer to its format.
