### ISSUE TITLE
Id vs Identifier in the name of a parameter

### ISSUE THREAD

**Issue by FabrizioMoggio** [camaraproject/Commonalities#16]
Many APIs use identifiers as parameters. In some API the suffix **Id** is used, while in other API the suffix **Identifier** is used.

See the issue in the Edge Cloud WG: "applicationId vs AppIdentifier" - https://github.com/camaraproject/EdgeCloud/issues/99.

For coherency in CAMARA, it would be better to fallow the same approach in each API.

**Proposal:** use the suffix **"Id"**

**Comment by rartych** [comment]
PR https://github.com/camaraproject/Commonalities/pull/23 merged
