### ISSUE TITLE
is UUID a must for x-correlator? 

### ISSUE THREAD

**Issue by jlurien** [camaraproject/Commonalities#166]
**Problem description**
Guidelines indicate that pattern for x-correlator is UUID but when added to OAS, only type: string is indicated

**Expected behavior**
Clarify in Guidelines whether UUID format is just a recommendation, or remove pattern and leave ir completely free for clients to choose, or include pattern or format  in OAS

**Comment by PedroDiez** [comment]
Understood the need of aligment. Probably there is no need of limiting the format of the x-correlator to be an UUID, so it could be admitted the use of a generic string, and align it accordingly in the guidelines.

**Comment by nickvenezia** [comment]
I vote to keep it open.

**Comment by PedroDiez** [comment]
@shilpa-padgaonkar, @eric-murray, would be fine from your view to have x-correlator as open string?

**Comment by shilpa-padgaonkar** [comment]
@PedroDiez Fine from my view.

**Comment by jlurien** [comment]
PR created to fix this: https://github.com/camaraproject/Commonalities/pull/168

**Comment by nickvenezia** [comment]
I believe it is an acronym for a unique identifier and is a field where multiple identifiers can be plugged into.
Sent from my iPhone

On Apr 15, 2024, at 10:12 AM, Rafal Artych ***@***.***> wrote:

﻿

Closed #166<https://github.com/camaraproject/Commonalities/issues/166> as completed via #168<https://github.com/camaraproject/Commonalities/pull/168>.
