### ISSUE TITLE
Broken link in Commonalities v0.3.0 Design Guidelines

### ISSUE THREAD

**Issue by hdamker** [camaraproject/Commonalities#167]
**Problem description**

The link within [line 874 of the Design Guidelines](https://github.com/camaraproject/Commonalities/blame/4c798ce02406076dcc11058d5a5a819ff4af8fb4/documentation/API-design-guidelines.md#L874) is broken. It points to https://github.com/camaraproject/IdentityAndConsentManagement/tree/main/documentation/CAMARA-AuthN-AuthZ-Concept.md in `main` branch of ICM but was there deleted after release 0.1 of IC&M.

**Expected behavior**

Within release v0.3.x of Commonalities the link should point either to https://github.com/camaraproject/IdentityAndConsentManagement/blob/release-0.1.0/documentation/CAMARA-API-access-and-user-consent.md or https://github.com/camaraproject/IdentityAndConsentManagement/blob/release-0.1.0/documentation/CAMARA-AuthN-AuthZ-Concept.md

It need to be corrected also in the `main` branch (v0.1 is still the current release of IC&M)

**Alternative solution**

The proposed solution approach in https://github.com/camaraproject/IdentityAndConsentManagement/issues/139 would also address the issue here in Commonalities.

**Additional context**

https://github.com/camaraproject/IdentityAndConsentManagement/blob/release-0.1.0/documentation/CAMARA-AuthN-AuthZ-Concept.md has the same issue ... it is also pointing to the deleted file https://github.com/camaraproject/IdentityAndConsentManagement/tree/main/documentation/CAMARA-AuthN-AuthZ-Concept.md in `main`of ICM.

**Comment by rartych** [comment]
The issue will be resolved with the alternative solution described in https://github.com/camaraproject/IdentityAndConsentManagement/issues/139

**Comment by hdamker** [comment]
Corrected for v0.3.0 with https://github.com/camaraproject/IdentityAndConsentManagement/pull/147. Please ensure that the next release won't contain links to unreleased versions of documents (aka "main" branch).

**Comment by hdamker** [comment]
@rartych this issue can be closed, fixed with https://github.com/camaraproject/IdentityAndConsentManagement/pull/147

**Comment by rartych** [comment]
Closing as indicated above.
