### ISSUE TITLE
Commonalities: request improvements to changelog standards

### ISSUE THREAD

**Issue by murthygorty** [camaraproject/Commonalities#17]
Hi, request the following improvements to changelog as a standard for API (example [link](https://github.com/camaraproject/DeviceStatus/blob/main/CHANGELOG.md) for DeviceStatus):

- Include date for when the version was released. This gives an idea on how long a version is out there.
- include common reference to definitions (for example, why is this considered pre-release). The benefit of including a reference is that an API is fully-contained from a Consumer and Producer perspective. Someone doesn't need to fully understand all aspects/branches/inner-workings of Camara to quickly benefit from it.

cc: @gmuratk

**Comment by ShutingQing** [comment]
Agree. We need to have a uniform and clear standard for changelog.

**Comment by murthygorty** [comment]
Hi all, regarding the main topic, can we get confirmation that the date from release is the date of the release and not the date of the PR (prior to approvals and reviews)?

Th problem statement I am trying to address is that as a carrier developer I would like to know the date of a particular version  *release*

**Comment by shilpa-padgaonkar** [comment]
@murthygorty : yes, its date of the release.
If this answers your question for the issue, kindly close the issue.

**Comment by murthygorty** [comment]
That's perfect - thanks for confirming @shilpa-padgaonkar 
For example, QoD 0.8.1 was released on Jan 27
<img width="252" alt="image" src="https://github.com/camaraproject/Commonalities/assets/19613159/dbff9c84-9715-4175-9467-af4abb3e422a">
