### ISSUE TITLE
Commonalities release 0.4.0 scope

### ISSUE THREAD

**Issue by rartych** [camaraproject/Commonalities#175]
**Problem description**
The next release of Commonalities should be the base for Fall24 CAMARA meta-release.

**Expected action**
The **M0** milestone (scope definition of the release should be achieved in the next Commonalities meeting on 15/04 

**Additional context**

The timeline for Fall24 - https://wiki.camaraproject.org/display/CAM/Meta-release+Fall24
![image-2024-4-4_16-7-4](https://github.com/camaraproject/Commonalities/assets/121048129/eac86740-5ad7-4825-9f6d-fb8ac8016ab4)

**Comment by jlurien** [comment]
Hi @rartych,

If I understood correctly, M0 it is the kick-off milestone. The definition of scope should be achieved by M1 (Agree on the scope of commonalities.). 
https://wiki.camaraproject.org/display/CAM/CAMARA+Release+Process

**Comment by PedroDiez** [comment]
Hi, 

One doubt, which would be the way of working(*) to settle initial the list of functionalities (scope) to be included within a given Release?

- Commonalities
- I&CM
- Every WG

(*) With way of working I refer to specific "documentation" it has to be considered:
- List the Issues that want to be covered and, if wanted to cover new Issues to be generated before the Milestone X?
- Also consider Existing PRs?
- Any other considerations?

**Comment by rartych** [comment]
With previous releases we have used list of issues and PRs that should be resolved within given release. So currently we have following topics:

- **Error responses** 
   - PR #145
   - Issue #127 
   - Issue #128
   - Issue #156 
   - Issue #180 

- **Test definitions**
  - Issue #158

- **Evolved model of event subscription**
  - Issue #149 : 
    - Issue #150
    - Issue #151 
    - Issue #153
    - Issue #154 
    - Issue #155 
    - PR #177
  - Issue #140

- **CAMARA_common.yaml cleanup**
   - PR #120
   - PR #168
   - PR #174
 
- **Release Management issues**
   - [Add guidance for Info object in apis](https://github.com/camaraproject/ReleaseManagement/issues/15)
   - [Readiness Checklist step 6 update proposal](https://github.com/camaraproject/ReleaseManagement/issues/16)
   - [API Versioning - Aggregation](https://github.com/camaraproject/ReleaseManagement/issues/14)
   - [How to manage version for a API family release](https://github.com/camaraproject/ReleaseManagement/issues/12)
   - [Remove basePath in servers.url as variable](https://github.com/camaraproject/ReleaseManagement/issues/17)


The scope should be agreed in Commonalities by M1 (30/04), but I think it should be ready for review by TSC (18/04).

**Comment by PedroDiez** [comment]
Would also like to propose: [x-correlator_support_guidelines_in_notifications](https://github.com/camaraproject/Commonalities/pull/170)

**Comment by eric-murray** [comment]
I would exclude #156 from the scope of v0.4.0 as I don't see any consensus being reached on that issue.

**Comment by rartych** [comment]
@PedroDiez @eric-murray I have modified the list in https://github.com/camaraproject/Commonalities/issues/175#issuecomment-2056775929 according to your comments.

**Comment by shilpa-padgaonkar** [comment]
Based on #185 , we should exclude #150 #151

**Comment by hdamker** [comment]
From TSC meeting minutes of May 2nd: 

- In the commonalities call on 29.04 [2024-04-29 Commonalities WG Minutes](https://wiki.camaraproject.org/display/CAM/2024-04-29+Commonalities+WG+Minutes), the scope of 0.4.0 has been finalized and includes the below topics
  - Error responses
  - Enhancement of Test Definitions
  - Subscriptions
  - Linting ruleset update
  - Wildcard scopes
  - Few other smaller issues
- Some issues have been labelled as backlog to keep them out of scope of 0.4.0

This scope is now reflected within https://github.com/camaraproject/Commonalities/issues/175#issuecomment-2056775929

**Comment by rartych** [comment]
Updated list of scope topics (points removed from the scope are deleted, PRs solving issues are added):

- **Error responses** 
   - ~~PR #145~~
   - PR #213 
     - Issue #127 
     - Issue #128
     - Issue #180 

- **Test definitions**
  - PR #203 
    - Issue #158

- **Evolved model of event subscription**
  - Issue #149  : 
    - Issue #185 
    - PR #189 
    - PR #198 
    - PR #177  
    - Issue #153
    - Issue #154 
    - Issue #155 
  - Issue #140
- **Event notifications**
    - Issue #170 
    - Issue #176 

- **CAMARA_common.yaml cleanup**
   - ~~PR #120~~
   - PR #168
   - PR #174
   - Issue #171 
 
- **Other issues**
  - Issue #191 
    - PR #194 
  - Issue #192 
    - PR #193 
  - Issue #188  

(The release management issues are driven from the release management WG)
- **Release Management issues**
   -  Issue #201 
      -  PR #214 
   -  Issue [Readiness Checklist step 6 update proposal](https://github.com/camaraproject/ReleaseManagement/issues/16)
   -  Issue [API Versioning - Aggregation](https://github.com/camaraproject/ReleaseManagement/issues/14)
      - PR #215 
   -  Issue [How to manage version for a API family release](https://github.com/camaraproject/ReleaseManagement/issues/12)
   -  Issue #199 
      -  PR #214 
   -  Issue #202
