### ISSUE TITLE
Align Common Design Model for Cloud Event specversion field in APIs Design

### ISSUE THREAD

**Issue by PedroDiez** [camaraproject/Commonalities#176]
**Problem description**
It has been detected a misaligment regarding the design format used to reflect `specversion` field in API that manage notifications.

Some of them settle `specversion` as en enum:
https://github.com/camaraproject/QualityOnDemand/blob/main/code/API_definitions/qod-api.yaml#L872
https://github.com/camaraproject/DeviceLocation/blob/main/code/API_definitions/geofencing.yaml#L614

While others leave as an open string (which should be filled to "1.0")
https://github.com/camaraproject/DeviceStatus/blob/main/code/API_definitions/device-status.yaml#L725
https://github.com/camaraproject/CarrierBillingCheckOut/blob/main/code/API_definitions/carrier_billing.yaml#L1040

**Expected behavior**
We at CAMARA should decide in a common design model across every APIs that manage notifications so as no doubts how to model this field in every API

**Alternative solution**
N/A

**Additional context**

Considering Design Guidelines https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#122-event-notification.

It is indicated the following:

> version of the specification to which this event conforms - must be "1.0"

Based on the decision, it would be needed to update:
-  Design Guidelines 
- Cloud Events artifact: https://github.com/camaraproject/Commonalities/blob/main/artifacts/notification-as-cloud-event.yaml#L183

**Comment by PedroDiez** [comment]
Given the fact that commonalities indicate 

> version of the specification to which this event conforms - must be "1.0"

Probably makes sense to adopt an enum, in order to avoid doubts about the value

**Comment by bigludo7** [comment]
@PedroDiez Yes make sense for me for the enum but I ping @patrice-conil to have his view as he crafted the file.

**Comment by PedroDiez** [comment]
As commented in Ad-hoc meeting and https://github.com/camaraproject/Commonalities/issues/185, PR is proposed to align behaviour based on "enum" categorization.
