### ISSUE TITLE
Revision of Chapter 6 Error Responses in API Design Guidelines

### ISSUE THREAD

**Issue by rartych** [camaraproject/Commonalities#180]
**Problem description**
There are a lot of questions and issues on Error Response format and content.
Currently the documentation lists the different error codes and cluster them into separate tables, depending on their nature: i) syntax exceptions, ii) service exceptions, and iii) server errors.
The tables do not contain HTTP status values which may introduce ambiguity.  There are also differences between the list and the examples in CAMARA_common.yaml

There are also questions on the Error Response format returned by OpenId Connect flows.

**Expected action**
Update Chapter 6 to provide clear requirements on Error Response content.
Decide what should be changed and aligned in [CAMARA_common.yaml](CAMARA_common.yaml).

Indicate when other standard formats can be used. 

**Additional context**
Resolution of Issue #127 can be extension/exemplification of Chapter 6 requirements.

**Comment by PedroDiez** [comment]
Think also Issues:
- [Issue#138](https://github.com/camaraproject/Commonalities/issues/138)
- [Issue#160](https://github.com/camaraproject/Commonalities/issues/160)
- [Issue#173](https://github.com/camaraproject/Commonalities/issues/173)

Have relation with this

**Comment by rartych** [comment]
I have prepared a table summarizing Chapter 6, CAMARA_common.yaml and QoD, Device Status and Location Verification error responses: https://wiki.camaraproject.org/display/CAM/Error+response+guidelines
Please note that the most of big differences is corrected by https://github.com/camaraproject/Commonalities/pull/174
I have also added table with proposals included in https://github.com/camaraproject/Commonalities/issues/127 and https://github.com/camaraproject/Commonalities/pull/145

We should think about changing chapter 6 by:
- adding HTTP status to the tables
- possibly remove some error responses - authentication is covered by OpenID Connect flows 
- adding table addressing https://github.com/camaraproject/Commonalities/issues/127 (here or in another document?)
- clarifying guidelines for error response fields

Please have a look @hdamker (QoD) @jlurien (Device Location) @bigludo7 (Device Status)

**Comment by bigludo7** [comment]
Thanks @rartych and fully support chapter 6 update in particular with #127 & #145 

One quick comment: for Device Location & Device Status we did not require update as `description` is not "normative".
