### ISSUE TITLE
X-Correlator or x-correlator

### ISSUE THREAD

**Issue by jlurien** [camaraproject/Commonalities#191]
**Problem description**
Guidelines in Commonalities specifies "X-Correlator" but almost all API specs define already "x-correlator"

**Expected behavior**
Even if header name is case insensitive and both options are interoperable, we should define a common behaviour for coherence, aligned with Guidelines.

As de facto API specs are using "x-correlator", it would be less effort to reflect this in the Guidelines.

It would be convenient to set a new linting rule to check that the header is included in the requests and responses, following the agreed format.

**Alternative solution**
Adjust all APIs using "x-correlator"

**Comment by rartych** [comment]
Agree  - to be considered in #188 
We have also pending action : "X-Correlator header definition to be added to CAMARA_common.yaml" in minutes - we should define a common format in https://github.com/camaraproject/Commonalities/blob/main/artifacts/CAMARA_common.yaml

**Comment by PedroDiez** [comment]
Agree to align

**Comment by bigludo7** [comment]
Agree to align for me also.
