### ISSUE TITLE
Common Design Model for Cloud Event datacontenttype field

### ISSUE THREAD

**Issue by rartych** [camaraproject/Commonalities#192]
**Problem description**
API Design Guidelines requirement is that `datacontenttype` field is  _media-type that describes the event payload encoding, must be `application/json` for CAMARA APIs_
In https://github.com/camaraproject/Commonalities/blob/main/artifacts/notification-as-cloud-event.yaml it is defined as follows:
```
datacontenttype:
          type: string
          description: 'media-type that describes the event payload encoding, must be "application/json" for CAMARA APIs'
```

**Possible evolution**
Define required value as enum - as the only possible value is "application/json" 

**Alternative solution**

**Additional context**
The similar `specversion` field is defined as enum with PR:
 -  https://github.com/camaraproject/Commonalities/pull/187

The `datacontenttype` field is optional , `specversion` field is mandatory

**Comment by PedroDiez** [comment]
Agree to follow same approach and define value as enum

**Comment by shilpa-padgaonkar** [comment]
+1

**Comment by patrice-conil** [comment]
+1

**Comment by PedroDiez** [comment]
Will be generating PR this week
