### ISSUE TITLE
Deprecate API-Readiness-Checklist.md

### ISSUE THREAD

**Issue by tanjadegroot** [camaraproject/Commonalities#202]
**Problem description**
The API-Readiness-Checklist.md is replaced by the new updated version which is located in the Release Management project 

**Expected action**
Deprecate or delete the API-Readiness-Checklist.md file from this repository 
Refer to new file resulting from https://github.com/camaraproject/ReleaseManagement/pull/29
Replace any references to the checklist in other documentation with the link to the new checklist document

**Additional context**

**Comment by hdamker** [comment]
@rartych Should be included into the 0.4.0 scope.
