### ISSUE TITLE
Update of API versioning section in API guidelines

### ISSUE THREAD

**Issue by tanjadegroot** [camaraproject/Commonalities#206]
**Problem description**
This update is to align the versioning section with the API versioning process described in release management Wiki.

**Expected action**
Review and agree on the proposed changes for merge into API-design-guidelines.md

**Additional context**
RM Wiki - [API versioning](https://wiki.camaraproject.org/x/a4BaAQ)

**Comment by rartych** [comment]
@tanjadegroot I propose to create PR here in Commonalities repo with proposed changes, then we can review them here.

**Comment by tanjadegroot** [comment]
@rartych that sounds good to me. I will prepare and propose the PR to Commonalities
