### ISSUE TITLE
Change to `application/cloudevents+json` for CloudEvent content-type

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/Commonalities#224]
**Problem description**
```yaml
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: "#/components/schemas/CloudEvent"
```

For the callbacks the request-body is declared as `application/json`.
Wouldn't it be good to define it as `application/cloudevents+json` ?

 
**Expected behavior**
```yaml
              requestBody:
                required: true
                content:
                  application/cloudevents+json:
                    schema:
                      $ref: "#/components/schemas/CloudEvent"
```

**Additional context**
https://github.com/camaraproject/Commonalities/blob/main/artifacts/camara-cloudevents/event-subscription-template.yaml#L110

**Comment by patrice-conil** [comment]
Hi @maxl2287,
I agree with you, to be compliant with cloud events specs we need to move to  application/cloudevents+json.
Patrice
