### ISSUE TITLE
Add 422 `UNIDENTIFIABLE_DEVICE` error in Service Exceptions table (§6.1)

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/Commonalities#249]
**Problem description**
Very small one....

In Appendix A: info.description template for device identification from access token we can read:

>  If the `device` object is not included in the request and 
the device information cannot be derived from the 3-legged access token, the server will return a 422 `UNIDENTIFIABLE_DEVICE` error.

.... but 422 `UNIDENTIFIABLE_DEVICE` error is not in Service Exceptions table (§6.1)

**Expected action**
Add 422 `UNIDENTIFIABLE_DEVICE` error in Service Exceptions table (§6.1)

**Additional context**
@rartych as it seems to be a straightforward i can probably craft the PR? wdyt?

**Comment by rartych** [comment]
Yes, I agree - it is correction for consistency between Chapter 6 and Appendix A.

**Comment by bigludo7** [comment]
Thanks @rartych - Will do.
As I'm not codeowner I cannot create branch and as I have already forked for https://github.com/camaraproject/Commonalities/pull/251 so will wait resolution of this later before to create a new one.

**Comment by PedroDiez** [comment]
Also would make sense to incorporate HTTP 422 to section 3.2 (as mentioned in https://github.com/camaraproject/Commonalities/discussions/248)
https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#32-http-response-codes

**Comment by jpengar** [comment]
> Add 422 UNIDENTIFIABLE_DEVICE error in Service Exceptions table (§6.1)

@bigludo7 @rartych @PedroDiez I would add it to Section 6.1 and to the table in Section 6.2, as with the other device-related error definitions.

**Comment by hdamker** [comment]
In addition it would good to add it also to artifacts/CAMARA_common.yaml for consistency.
