### ISSUE TITLE
Version within CAMARA_common.yaml shouldn't be "wip"

### ISSUE THREAD

**Issue by hdamker** [camaraproject/Commonalities#254]
**Problem description**

Within rc.1 the version in https://github.com/camaraproject/Commonalities/blob/f9f6c490bdfa6f5af42facf324fe069642257357/artifacts/CAMARA_common.yaml#L10 is "0.4.0-wip". 

**Expected behavior**

A non "wip" version should be set, and referred within the release description/changelog of rc.2

**Alternative solution**

**Additional context**

**Comment by rartych** [comment]
The whole `info` object in CAMARA_common.yaml need to be aligned with the changes introduced in API Design Guidelines.
https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#info-object

The problem we have with version field is that in Commonalities v.0.3.0 it was set to 0.4.0.
https://github.com/camaraproject/Commonalities/blob/release-0.3.0/artifacts/CAMARA_common.yaml#L10

As CAMARA_common.yaml  is not to be implemented, not increasing the version this time would not be very harmful.
Then we would get :
```
info:
  title: Camara common data types
  description: Common data types for Camara APIs
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.4.0
  x-camara-commonalities: 0.4.0
```

Increasing version field (it is mandatory in OAS):
 
```
  version: 0.5.0
  x-camara-commonalities: 0.4.0
```
looks confusing for me.

**Comment by hdamker** [comment]
As we introduced for APIs that the release numbering is independent from the (API) versioning, I personally wouldn't be confused if Commonalities would have artefacts which are diverging from the release number. In fact I would even expect the artefacts have their independent version numbers.

**Comment by rartych** [comment]
As it was discussed in Commonalities meeting decoupling of CAMARA_common.yaml version from Commonalities version allows to introduce changes even faster than Commonalities versions are released.
Changes will be introduced in https://github.com/camaraproject/Commonalities/pull/257 .
