### ISSUE TITLE
Replace internal links between Commonalities documents with relative links to stay within the same release tree / fork / release package

### ISSUE THREAD

**Issue by jpengar** [camaraproject/Commonalities#275]
**Problem description**

Commonalities documents in the repository contain links/references to each other, written as fully qualified URLs pointing to the main branch of Commonalities. 

A reader within a release tree would jump out of the tree into a potentially incorrect version. The same is true for someone who has downloaded the release package (zip file) of Commonalities.

**Expected behavior**

Use - as [recommend](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#relative-links) by GitHub - relative links instead.

e.g. 
`https://github.com/camaraproject/Commonalities/tree/main/artifacts/camara-cloudevents` in Commonalities/documentation
/API-design-guidelines.md document to be replaced with `/artifacts/camara-cloudevents` (link relative to the repository root).

**Alternative solution**

N/A

**Additional context**

This issue corresponds to the same problem raised in the ICM WG at https://github.com/camaraproject/IdentityAndConsentManagement/issues/187 and fixed in ICM [r0.2.0-rc.2](https://github.com/camaraproject/IdentityAndConsentManagement/releases/tag/r0.2.0-rc.2).

**Comment by PedroDiez** [comment]
I am generating this PR in this week. Expected to have at least for 14th August
