### ISSUE TITLE
Public release of v0.4.0

### ISSUE THREAD

**Issue by rartych** [camaraproject/Commonalities#282]
**Problem description**
The PR for the public release of 0.4.0 should be created and discussed in Commonalities call on **August 19th**, so that the TSC on 22nd can approve it (based on the recommendation from Commonalities and Release Management).

**Expected action**

- We need to resolve #274 and #275 before the public release.

- If any bugs are found the resolution should be prepared by  August 19th.

**Additional context**
**Aug 26th**: latest date that APIs should provide their final release PRs (with the public API version, either initial or stable)

**Comment by FabrizioMoggio** [comment]
In the API OAS, for M4, do we need to refer to:

x-camara-commonalities: 0.4.0

?

**Comment by rartych** [comment]
Yes.

The public release of 0.4.0 should be available end of this week

Rafał

**Comment by rartych** [comment]
Published under: https://github.com/camaraproject/Commonalities/tree/r0.4.0
