### ISSUE TITLE
Update the "sink" property description

### ISSUE THREAD

**Issue by PedroDiez** [camaraproject/Commonalities#289]
**Problem description**
Within Commonalities MetaRelease Fall 24. It has been agreed so far the unique use of HTTP protocol for "callback URLs"

Some in-advance decision has been made for QoD on Demand and Carrier Billing Checkout

**Expected behavior**
Update and align in commonalities artifacts the suitable wording for "sink" description:

`The address to which events shall be delivered, using the HTTP protocol.`

**Alternative solution**
Not considered so far, open to discussion in any case.

**Additional context**
[Issue opened in Carrier Billing Checkout]CarrierBillingCheckout/Issue#168(https://github.com/camaraproject/CarrierBillingCheckOut/issues/168)

Issue proposed for MetaRelease Spring 25 - https://github.com/camaraproject/Commonalities/issues/273

**Comment by bigludo7** [comment]
Hello @PedroDiez 

To fix this one the proposal is to correct the table [here](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#instance-based-implicit-subscription) to change the attribute description for the sink attribute.

Nothing to do on the event-subscription-template.yaml as the sink attribute description is already the right one.

Agreed on the resolution?
@rartych you can assign this one to me and tag subscriptions ;)

**Comment by PedroDiez** [comment]
Hi,

Agree to correct description on the table you mention @bigludo7 and i think also makes sense to align the wording in the event-subscription-template.yaml

https://github.com/camaraproject/Commonalities/blob/main/artifacts/camara-cloudevents/event-subscription-template.yaml#L297C24-L297C99

**Comment by bigludo7** [comment]
Thanks @PedroDiez - clear for me.
Will do
