### ISSUE TITLE
Sink credentials sent back as a part of API responses. 

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/Commonalities#296]
**Problem description**
For APIs where we have either implicit or explicit subscriptions, as a part of a successful response, we send back the sink credentials.
IMHO we should exclude this information from the response. 

**Expected behavior**
Do not send back sink credentials as a part of the API responses. 

**Alternative solution**

**Additional context**

**Comment by PedroDiez** [comment]
Related Issue [Design Guidelines should provide guidance about sinkCredentials in returned/retrieved subscription objects #276](https://github.com/camaraproject/Commonalities/issues/276)

**Comment by rartych** [comment]
Let's continue discussion in 

- https://github.com/camaraproject/Commonalities/issues/276

**Comment by rartych** [comment]
Closing as resolved in #313
