### ISSUE TITLE
Add additional HTTP status codes 415 and 429 to the API Design Guidelines 

### ISSUE THREAD

**Issue by eric-murray** [camaraproject/Commonalities#30]
**Problem description**
HTTP status codes 415 (Unsupported Media Type) and 429 (Too Many Requests) are used by some CAMARA APIs, but are not explicitly listed in the API Design Guidelines (even though the corresponding error codes `UNSUPPORTED_MEDIA_TYPE` and `TOO_MANY_REQUESTS` have been defined).

**Expected action**
HTTP status codes 415 and 429 should be explicitly added to the list of allowed codes

**Additional context**
I know that the design guidelines do not explicitly prohibit these status codes from being used, but the list of "common errors" is so long and already includes some pretty obscure errors that I think the list should include all status codes that are actually being used.

**Comment by shilpa-padgaonkar** [comment]
fine for me

**Comment by patrice-conil** [comment]
Fine for me too

**Comment by eric-murray** [comment]
OK. I'll create the PR.

**Comment by eric-murray** [comment]
PR #33
