### ISSUE TITLE
Support & Aligment of 504 Exception in CAMARA APIs 

### ISSUE THREAD

**Issue by PedroDiez** [camaraproject/Commonalities#308]
**Problem description**

Currently in CAMARA APIs the indication of Exception 504 (TIMEOUT) in APIs YAMLs is not aligned.

There are some APIs that document it whilst in others are not documented.

The exception is already documented in [CAMARA_common.yaml](https://github.com/camaraproject/Commonalities/blob/main/artifacts/CAMARA_common.yaml#L471)

And it is a scenario that may happen in any API.

**Possible evolution**

Aligned in every CAMARA WG to document this excepction in every APIs endpoints 

**Alternative solution**
N/A

**Additional context**
Background discussion in: https://github.com/camaraproject/Commonalities/pull/189#discussion_r1587124198

A child issue of this generic one is #291

**Comment by PedroDiez** [comment]
cc @rartych, @bigludo7

**Comment by bigludo7** [comment]
Hello @PedroDiez 
Works for Orange team.
