### ISSUE TITLE
Artifact for test plan scenarios for device/phoneNumber errors

### ISSUE THREAD

**Issue by jlurien** [camaraproject/Commonalities#323]
**Problem description**
In CAMARA we have guidelines for errors related to the management of device/phoneNumber inputs, and test plans should include scenarios to test that those guidelines are applied for APIs with such an input. 

Test guidelines give high level recommendations but they do not define specific scenarios, so different test definitions may end up with different scenarios for the same use case.

**Possible evolution**
Create a common artifact for these scenarios, here in Commonalities, that can be directly applied, or with some minor adaptation, to test plans. This would ease the creation of test plans and assure coherence. 

**Additional context**
This would be a first artifact but we may create additional artifacts for the testing of other functionalities that are shared by several APIs and have also common guidelines, such as:

* Subcriptions
* Events
* Common errors dealing with authentication/authorization

**Comment by bigludo7** [comment]
Fully aligned with the proposal objectives.

I've raised issue #293 some time ago for same topic but for the subscriptions.
