### ISSUE TITLE
servers field in event-subscription-template.yaml not in line with API guidelines

### ISSUE THREAD

**Issue by tanjadegroot** [camaraproject/Commonalities#326]
**Problem description**
The servers field in the example file event-subscription-template.yaml does not follow the API guidelines.

**Expected behavior**
Change the example to follow the API guidelines to avoid introducing misalignment by coping from this example. In particular:
- update the servers field

**Comment by rartych** [comment]
Yes, indeed it needs correction, the guidelines are following:

https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#servers-object
https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#52-api-version-in-url-oas-servers-object

@bigludo7 Can we resolve it within https://github.com/camaraproject/Commonalities/pull/313 ?

**Comment by bigludo7** [comment]
Sure !
Please assign it to me.

**Comment by bigludo7** [comment]
Request took into account in #313 :)
