### ISSUE TITLE
Update minimum criteria checklist with the recent decision about documentation in spec file

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/Commonalities#34]
**Problem description**
Currently, the minimum criteria checklist points to the now outdated documentation template rather than specify that the spec file will be self-sufficient in terms of documentation. This change would be good to be in before we create the release.

**Expected behavior**
PR with the above stated change in minimum criteria checklist.

**Alternative solution**

**Additional context**

**Comment by shilpa-padgaonkar** [comment]
Do we also prefer removing the outdated documentation template from the deliverables?

**Comment by patrice-conil** [comment]
@shilpa-padgaonkar,
IMHO, that sounds like a good idea.

**Comment by FabrizioMoggio** [comment]
For the APIs that already have an API_Documumentation.md file, what do we need to do? Do we continue to maintain and update it or we delete it when a new YAML version is released?
