### ISSUE TITLE
Cloud Event media type problem: "cloudevents+json"

### ISSUE THREAD

**Issue by FabrizioMoggio** [camaraproject/Commonalities#345]
**Problem description**
in the template for Cloud Event (https://github.com/camaraproject/Commonalities/blob/main/artifacts/notification-as-cloud-event.yaml) it is defined in line 81: "application/cloudevents+json".

This media type is not included in the list of standard media-type: https://www.iana.org/assignments/media-types/media-types.xhtml

**Expected behavior**
modify line 81 as "application/json"

**Additional context**
https://cloud.google.com/eventarc/docs/cloudevents-json

**Comment by rartych** [comment]
The issue was discussed previously:
https://github.com/camaraproject/Commonalities/pull/43#discussion_r1397706252

**Comment by FabrizioMoggio** [comment]
Got it, we can manage it.
