### ISSUE TITLE
Errors Documented in `notification-as-cloud-event.yaml`

### ISSUE THREAD

**Issue by PedroDiez** [camaraproject/Commonalities#348]
**Problem description**
While reviewing PR #329 and based on [this](https://github.com/camaraproject/Commonalities/pull/329#discussion_r1856562243) comment, think maybe we need some actions with regards to the errors documented in the event notification artifact.

1. Should we remove 500, 503 errors from the artifact (i.e. we assume any server exception is implicitly managed by the API consumer, in the same fashion as we do for Telco Operator)? And therefore align it in [API Design guidelines](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#error-definition-for-event-notification)?

2. As in artifact are documented 400, 401, 403, 410, 429, should we considered all of them as mandatory? And therefore align it in [API Design guidelines](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#error-definition-for-event-notification)?

Parent Issue: #273 

**Expected behavior**
Based on the output discussion. 

Initially the proposal would be:
* Remove Errors 500, 503 from the artifact. Align in API Design Guidelines
* Consider Errors 410 and 429 as mandatory for event notifications. Align in API Design Guidelines

**Alternative solution**
Not evaluated

**Additional context**
Alignment of Errors the CAMARA guidelines
Based on output I can generate a PR or take advantage of ongoing PR #329

**Comment by PedroDiez** [comment]
cc @rartych, @patrice-conil, @shilpa-padgaonkar, @bigludo7, @eric-murray 
WDYT?

**Comment by bigludo7** [comment]
Hello @PedroDiez 
To be sure to be aligned you mean in this file: https://github.com/camaraproject/Commonalities/blob/main/artifacts/notification-as-cloud-event.yaml ?
If yes fully aligned. I can do the PR.

**Comment by PedroDiez** [comment]
> Hello @PedroDiez To be sure to be aligned you mean in this file: https://github.com/camaraproject/Commonalities/blob/main/artifacts/notification-as-cloud-event.yaml ? If yes fully aligned. I can do the PR.

Hello @bigludo7, Yes i refer to that document
