### ISSUE TITLE
Common.yaml: Generic503 example does not use expected value

### ISSUE THREAD

**Issue by Kevsy** [camaraproject/Commonalities#362]
**Problem description**

The Generic503 schema states:
```
                  code:
                    enum:
                      - SERVICE_UNAVAILABLE
```
but the example uses:

```
                code: UNAVAILABLE
```
...which is causing the Spectral linter to throw:

```
"code" property must be equal to one of the allowed values: "SERVICE_UNAVAILABLE". Did you mean "SERVICE_UNAVAILABLE"?
```

**Expected behavior**

Change the example to `code:  SERVICE_UNAVAILABLE`

**Alternative solution**

**Additional context**

**Comment by eric-murray** [comment]
See #359. `UNAVAILABLE` is actually the correct code.

**Comment by Kevsy** [comment]
Got it -thanks @eric-murray
