### ISSUE TITLE
API Design for "Resource-based subscription"

### ISSUE THREAD

**Issue by PedroDiez** [camaraproject/Commonalities#44]
**Problem description**
Within Commonalities API design guidelines, it has been indicated a common way to define the support for notifications model. 
https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#12-subscription-notification--event

In "Resource-based subscription" when applying this model to the API design, several approaches are seen:
Model 1:
- Device Location Verification (separate API): https://github.com/camaraproject/DeviceLocation/pull/74/files

Model 2:
- Device Status (functionlity embebbed within API): https://github.com/camaraproject/DeviceStatus/blob/main/code/API_definitions/device-status.yaml#L134

We think it is reasonable to have a common way to design this features.
Our proposal is to align the approach and use a common model when including this features in WG APIs families.

This will require some indication in Commonalities Guidelines. Once some conclusion is reached.

**Possible evolution**
Our proposal is to follow Model 1 when designing "Resource-based subscription" in API families. Main reasons to support this model are:

- Design 'simpler' APIs, avoiding APIs with many endpoints, that make its implementation and availability complex.

- Have more 'flexibility' to evolve "Resource-based subscription" separately, so also roadmaps can be decoupled in order to expose this functionality. In this way, timeline for API functionality and subscriptions feature can be decoupled so Telco Operators can provide them in a more agile way depending on its market needs.

- Notification subscriptions systems can be from technical perspective decoupled from API BE Logic, so having different "server url" exposition. That is, the logic of subscription management is managed separately from the API BE logic, as the main "core" of this logic is to identify when an event occurs if there is a matching susbcription for that event and if so, send a notification to the notificationURL indicated   

Would like to see the view about this point  within CAMARA

**Comment by PedroDiez** [comment]
@shilpa-padgaonkar, @hdamker, @eric-murray, @patrice-conil, @bigludo7
RubenBG7

cc @RubenBG7, @jpengar, @jlurien

**Comment by patrice-conil** [comment]
HI @PedroDiez,
We (@bigludo7 and I) also believe that model 1 is the way to go to clearly define that the /notifications endpoint will be called from the consumer side of the API.
As this model is not well supported by code generators (openapi-generator or swagger-generator for example), we proposed to define a separate OAS specification for the /notifications endpoint that consumers could use to generate their server part.
We have made two joint proposals in commonalities that you can review and comment on.

**Comment by PedroDiez** [comment]
Thanks @patrice-conil, I will review them

**Comment by shilpa-padgaonkar** [comment]
@PedroDiez : I would also like to extend my full support for model 1. The decoupling point you have mentioned is a very important one IMHO.

**Comment by PedroDiez** [comment]
So far, seems Model 1 is preferred, that is, define a separate API functionality for resource-based susbcription.
If no further comments, I will be preparing a PR to Commonalities API design guidelines next in order to reflect this.

**Comment by eric-murray** [comment]
Hi @PedroDiez

Maybe the reason that there are not many comments on this issue is that it is the holiday season, and companies are taking longer to confer internally on this.

Any I do think it important that we get the consolidated views of companies rather than individual developers on this, for otherwise we risk decisions being made based on the opinions of individual developers when other developers from that same company are expressing contradictory views within individual API sub-projects.

For example, the issue of whether APIs should adopt multiple endpoints within an API or multiple APIs was originally discussed within Commonalities [here](https://github.com/camaraproject/WorkingGroups/discussions/218). As the issue did not get any traction, it was agreed to discuss it within individual sub-projects.

The discussion and decision within Device Status can be found [here](https://github.com/camaraproject/DeviceStatus/discussions/55). The agreement was that additional use cases for Device Status should be combined within a common API. This decision was supported by Orange and Deutsche Telekom.

But now we risk a requirement that subscriptions be included in a separate API for exactly the same reasons that were discussed and rejected during the discussion within Device Status.

So this issue should be kept open until after the holiday season, when each company will have had the opportunity to reach and express an internal consensus. This will help to avoid a decision being made here which contradicts decisions made by the same company in the individual sub-projects.

**Comment by PedroDiez** [comment]
Hi @eric-murray 

Get your point, Let's keep open until other companies reflect here also their view

**Comment by PedroDiez** [comment]
Hi all,

Just recovering this issue, and let me extend with some relationship with [Issue#8](https://github.com/camaraproject/Commonalities/issues/8)

We have two models for subscription:
- Resource-based (this issue is related to it)
- Instance-based (e.g. QoD model)

And we are trying to define a common model for the notification to the API consumer (Issue#8 scope).

---

- One of the topics of Issue #8, reflected in related PRs 41 and 43, is how to indicate the "real" payload carried within the generic framework it is been defined and that it specific depending on the context of the event (i.e. the API the event is related to).

In Implicit-Based models, think is well addressed with the indication of callback model within the API endpoint that implicitly has events related (e.g. QoD: https://github.com/camaraproject/QualityOnDemand/blob/main/code/API_definitions/qod-api.yaml#L99).

In Resource-based Models, think it could be some indication within API Proposal. Like an (informative) endpoint that determines the specific payload in the context of the involved API. It would not be the real endpoint because that one is the one defined via Notifications API (PR#41, PR#43 scope)

This is also aligned with the proposal in Model1. Have checked comments and historic background and (if not wrong), it seems that DT, ORA, VF, TEF would be aligned to go for Model 1. 

@shilpa-padgaonkar, @patrice-conil, @bigludo7 have commented in that way, and @eric-murray i understand your comment/concern raised and checking VF view was also to have a separate functionality.

Therefore, my feeling is that we have initial consensus to move towards Model 1 and the pending point here would be how to indicate in this model the specific format of the event to be signalled via common/traversal notifications API

**Comment by eric-murray** [comment]
Hi @PedroDiez
Yes, I discussed this internally, and Vodafone's preference is for Model 1. Hopefully this topic can be discussed at this week's Commonalities meeting so that we can get the explicit agreement of other companies.

**Comment by patrice-conil** [comment]
Hi @PedroDiez, @eric-murray 
Idea we have with @bigludo7 with issue #8 is to provide a "base spec" each API could use to extend with its proper event models.

**Comment by PedroDiez** [comment]
Hi,

understood @patrice-conil. 

And we need to decide in the use of a common model: PR#41 or PR#43. (that is at least my understanding)

**Comment by bigludo7** [comment]
Not adding comment but trying to separate the topics as we have a commonalities meeting tomorrow and let's see what we can solve

1. Have a distinct swagger file to define the **generic** CAMARA notification (tracked in issue #8) - We have so far a lot of positive comment to have this separate notification file (format of this file is point 2)

2. If decision on separate notification file we need to decide the format: "CAMARA Specific" #41  or based on Cloud Event #43 . I got the feeling that we have more positive feedback about using **Cloud Event**.

3. use of `callbacks`: OAS definition (like in QoD API) or add a specific /notification endpoint (like in Device Status). Got the feeling that we have a consensus to follow the 'callback pattern. In this callback event specific to the API are described but of course use the generic template (point 1) and follow format defined in point 2.

4.  Last but not least the last point mentioned by @PedroDiez about having a specific swagger for Resource-based subscription. As mentioned by @eric-murray I'm not sure this is an easy point to solve as we have already a lot of debates inside commonalities and inside device status WG.

As a lot of API working Group (device location, Device status for example) are waiting for Notification design decision we should perhaps try to get consensus to points 1 to 3 (Decisions there could be reflected on the design guideline document) and park 4 for later.

@PedroDiez @patrice-conil @eric-murray @shilpa-padgaonkar  WDYT?

**Comment by PedroDiez** [comment]
Feedback for every Point:

1. Fully aligned, have a common / unique interface for notifications to an API client is indeed ky point to make a common traversal implementation for any Operator. J

Just to set difference in scope of Issue #8 and Issue#44

![image](https://github.com/camaraproject/Commonalities/assets/6905728/6c028ed7-42cd-422b-87f7-f8629cafdfb5)


2. In this bullet, the key point is to decide which model to apply. We have to decide on one, and apply in the same way for every API. Same the have feeling, and even our current model is closer to PR#41, we are fine to go for Cloudevent Model if we have consensus here.


3. Now i understood your comment about (@bigludo7) Model 1 and Model 2 (I will comment on bullet 4, because I opened this Issue with other perspective, nonetheless this is also another point to be aligned and have also doubts about @shilpa-padgaonkar understood in the same view as you). Probably the use of callbacks is cleaner and can be used in both models:

- Implicit-based: making callback reference in the endpoint that have events associated
- Resource-based: making callback reference in the POST /subscriptions endpoint

One thing that we have to bear in mind is that if we go for CloudEvents Model, we will have to adapt the callback definitions in the APIs as they are mainly based in PR#41 proposal.


4. When opened this Issue was in the context of opening discussion about defining "Resource-Based" suscription model as a separate API in any scenario. @eric-murray got the point and referenced to the thread and background context within Device Status WG, and now I understand @bigludo7 your comment about Model 1 and Model 2 that was related to bullet 3. Have doubt @shilpa-padgaonkar if your comment was in the context raised the issue.

Anyway, I am fine to prioritize Points 1,2,3. 

And make follow-up for point 4. Let's talk tomorrow about this point 4

**Comment by rartych** [comment]
Please provide additional comments till **31st of August**. Then @bigludo7 will prepare PR related  to points 1,2,3 to be decided by Technical Steering Committee.

**Comment by eric-murray** [comment]
Please provide any additional reviews or comments by 15th September

**Comment by jordonezlucena** [comment]
@bigludo7 (@PedroDiez is on vacation): just to confirm that the scope of #56 is 

> Not adding comment but trying to separate the topics as we have a commonalities meeting tomorrow and let's see what we can solve
> 
> 1. Have a distinct swagger file to define the **generic** CAMARA notification (tracked in issue [Provides specific CAMARA OAS for notification event #8](https://github.com/camaraproject/Commonalities/issues/8)) - We have so far a lot of positive comment to have this separate notification file (format of this file is point 2)
> 2. If decision on separate notification file we need to decide the format: "CAMARA Specific" [Add generic notification OAS file #41](https://github.com/camaraproject/Commonalities/pull/41)  or based on Cloud Event [Define CAMARA Event using cloudevents in OAS notifification #43](https://github.com/camaraproject/Commonalities/pull/43) . I got the feeling that we have more positive feedback about using **Cloud Event**.
> 3. use of `callbacks`: OAS definition (like in QoD API) or add a specific /notification endpoint (like in Device Status). Got the feeling that we have a consensus to follow the 'callback pattern. In this callback event specific to the API are described but of course use the generic template (point 1) and follow format defined in point 2.
> 4. Last but not least the last point mentioned by @PedroDiez about having a specific swagger for Resource-based subscription. As mentioned by @eric-murray I'm not sure this is an easy point to solve as we have already a lot of debates inside commonalities and inside device status WG.
> 
> As a lot of API working Group (device location, Device status for example) are waiting for Notification design decision we should perhaps try to get consensus to points 1 to 3 (Decisions there could be reflected on the design guideline document) and park 4 for later.
> 
> @PedroDiez @patrice-conil @eric-murray @shilpa-padgaonkar WDYT?

@bigludo7 (@PedroDiez is on vacation): just to confirm that the scope of #56 is circumscribed to points 1-3. Is it correct?

**Comment by bigludo7** [comment]
@jordonezlucena 

> just to confirm that the scope of https://github.com/camaraproject/Commonalities/pull/56 is circumscribed to points 1-3. Is it correct?

Yes !

**Comment by PedroDiez** [comment]
Hi, 

I propose to close this Issue. Main points have been aligned and addressed within https://github.com/camaraproject/Commonalities/pull/56

@bigludo7, @shilpa-padgaonkar, @rartych, @eric-murray (just thumbs up emoji is enough)
cc @jordonezlucena

**Comment by PedroDiez** [comment]
Closing this issue
