### ISSUE TITLE
Using kebab-case for security scope is not easily machine readable

### ISSUE THREAD

**Issue by RandyLevensalor** [camaraproject/Commonalities#46]
**Problem description**
In the [Security Implementation](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#102-security-implementation) it suggests using kebab-case for the scope.

The provided example `explore-content-modules-users-read` is not easily machine readable.

**Expected action**
Ideally, a developer would be able to use the .split('-') operation on the scope and get three strings in return.  One for each of the three elements.  <API_name>-<Resource>-<Permission>.  Since the elements are also kebab-case, the split command would return 5 strings from the split operation.  And then would need to have logic that would know what the expected API name and resource name are.

If there was one api named explore and another named explore-modules, the code would need to be aware of this and couldn't use a shared library for parsing the the permissions.

Using snake case or camel case for the three elements and kebab-case for combining the elements would resolve this.

**Additional context**
To date, all of the APIs have a single name, so identifying the API name or updating the mechanism the the API name shouldn't impact any current APIs.

It's also unclear if a multi word api name should be kebab-case or another format.  Section 4.1 seems to hint that it should be kebab-case.

> URI with lowercase and hyphens. URIs must be "human readable" to facilitate identification of the offered resources. Lowercase words and hyphenation (kebab-case) help achieve this best practice. For example: /customer-segments

These may not be items that there is agreement to change, but at the very least it would be appreciated to make the documentation explicit on these topics.

**Comment by bigludo7** [comment]
@RandyLevensalor For the device location API, @jlurien proposed to use format `api_name:[resource:]action` for scope in security scheme (use of `:` as separator). Is it something working for you and that we can propose for all APIs?

There is also an open issue on same topic in Number verify (https://github.com/camaraproject/NumberVerification/issues/49)

**Comment by jlurien** [comment]
We are preparing a proposal for common guidelines around scopes naming and security/securitySchemes specification. We'll open a new issue for this.

**Comment by jlurien** [comment]
New issue created: https://github.com/camaraproject/Commonalities/issues/53
