### ISSUE TITLE
Small fix in security section of API guidelines document 

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/Commonalities#5]
**Problem description**

The security section of the document includes the below line 

Basic idea in terms of security is to understand that various types of data will require different levels of security, depending on the confidentiality of the data you are trying to obtain and the level of trust between _**Telefónica_** and the consumer.

**Expected behavior**
Telefonica reference needs to be changed to a more generic term.

**Alternative solution**

**Additional context**

**Comment by patrice-conil** [comment]
Hi @shilpa-padgaonkar,
Maybe something like  "Resource or Service Provider" ?
