### ISSUE TITLE
Unify specification of `securitySchemes`, `security` and scopes

### ISSUE THREAD

**Issue by jlurien** [camaraproject/Commonalities#53]
## **Problem description**

Currently, there is no consistency across WG regarding definition of the `securitySchemes` types, and about providing and naming scopes to protect operations. 

This table summarizes the situation, listing which `securitySchemes` are considered per WG, and which scopes are defined for that type (linked by means of `security` property):

| WG | oauth2/<br>clientcredentials | oauth2/<br>authorizationCode | openIdConnect |
| :--- | :--- | :--- | :--- |
| AnonymisedSubscriberIdentifier | Without scopes | - | - |
| BlockChainPublicAddress (PR) | - | `blockchain-public-address-read`<br>`blockchain-public-address-create`<br>`blockchain-public-address-delete` | - | - |
| CarrierBillingCheckOut | Without scopes | `carrier-billing-payments-create`<br>`carrier-billing-payments-prepare`<br>`carrier-billing-payments-confirm`<br>`carrier-billing-payments-cancel`<br>`carrier-billing-payments-read` | - |
| DeviceIdentifier | Without scopes | - | - |
| DeviceLocation | Without scopes | `location-verification:verify` | - |
| DeviceStatus | Without scopes | `device-status-roaming-read`<br>`device-status-roaming-event` | - |
| EdgeCloud | `nbi-mgmt`<br>`edge:discovery:read`<br>`edge:serviceprofile:read`<br>`edge:serviceprofile:write`<br>`edge:serviceregistry:read`<br>`edge:serviceregistry:write`<br>`edge:traffic-influences:read`<br>`edge:traffic-influences:write` | - | - |
| HomeDevicesQoD | - | - | `home-devices-qod-qos-write` |
| NumberVerification (CAMARA) | - | - | `number-verification-verify-read`<br>`number-verification-share-read` |
| OTPValidationAPI | `one-time-password-sms:send-validate` | - | - |
| SimSwap (CAMARA) | Without scopes | `retrieve-sim-swap-date`<br>`check-sim-swap` | - |
| QualityOnDemand | Without scopes | `qod-sessions-read`<br>`qod-sessions-write`<br>`qod-sessions-delete`<br>`qod-profiles-read` | - |

## **Possible evolution**
Unify specification of `securitySchemes`, `security` and scopes across all WGs with common guidelines. Exceptions to the guidelines should be avoided and justified.

### Use of openIdConnect for `securitySchemes`

Generally, OpenID Connect is the protocol to be used for securitization. Each API spec will define the following entry in `securitySchemes`, as shown in [CAMARA-AuthN-AuthZ-Concept.md](https://github.com/camaraproject/IdentityAndConsentManagement/blob/main/documentation/CAMARA-AuthN-AuthZ-Concept.md#documentation-and-specs-) document:
```
components:
  securitySchemes:
    openId:
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
```

The value for `openIdConnectUrl` in the CAMARA spec is an example, that must be substituted by the specific discovery endpoint for OIDC protocol of the API provider, when the API is exposed in one of its environments.

### Use of `security` property

Generally, each operation will be protected by a scope and it will include a `security` property with a single element in the array:

```
paths:
  {path}:
    {method}:
      ...
      security:
        - openId:
            - {scope}
```

The key is arbitrary in OAS, but convention in CAMARA is to name it `openId`. This key must be same defined in the `components.securitySchemes` section.
The {scope} is the specific scope defined to protect this operation. It must follow the syntax specify below.

### Scope naming

Define a scope per API operation with the structure:

`api-name:[resource:]action`

where

* `api-name` is the API name specified as the base path, prior to the API version, in the `servers[*].url` property. For example, from `/location-verification/v0`, it would be `location-verification`.

* `resource` is optional. For APIs with several `paths`, it may include the resource in the path. For example, from `/qod/v0/sessions/{sessionId}`, it would be `sessions`.

* `action`: There are two cases:
  - For POST operations with a verb, it will be the verb. For example, from `POST /location-verification/v0/verify`, it would be `verify`.
  - For CRUD operations on a resource in paths, it will be one of:
    - `create`: For operations creating the resource, typically `POST`.
    - `read`: For operations accessing to details of the resource, typically `GET`.
    - `update`: For operations modifying the resource, typically `PUT` or `PATCH`.
    - `delete`: For operations removing the resource, typically `DELETE`.
    - `write` : For operations creating or modifying the resource, when differentiation between `create` and `update` is not neeed.

#### Examples

| API | path | method | scope |
| --- | --- | --- | --- |
| location-verification | /verify | POST | `location-verification:verify` |
| qod | /sessions | POST | `qod:sessions:create`, or<br>`qod:sessions:write` |
| qod | /qos-profiles | GET | `qod:qos-profiles:read` |

**Comment by patrice-conil** [comment]
Hi @jlurien,
Nice work, I totally agree with you.

**Comment by PedroDiez** [comment]
Gathering main comments so far, raised during Commonalities 24/AGO meeting:

- Commented by @bigludo7: 

> How to deal with scenarios where a POST method is designed but really underlying API Logic is a "read" information process, Example: https://github.com/camaraproject/DeviceStatus/blob/main/code/API_definitions/device-status.yaml#L86

- Commented by @eric-murray 

> How to deal with scenarios where there is a fine-grained level rather than action. That is when within response resource information only a set of parameters/information has to be allowed to be returned. 
Example: https://github.com/camaraproject/DeviceStatus/blob/main/code/API_definitions/device-status.yaml#L86, to allow the return only of the countryCode but not the countryName


Please, @bigludo7, @eric-murray do not hesitate to add/clarify any topic you may consider of relevance

**Comment by jlurien** [comment]
About the use of openIdConnect for securitySchemes, is there any concern?

**Comment by jlurien** [comment]
I will create a new PR to modify guidelines with this new proposal

**Comment by shilpa-padgaonkar** [comment]
To all participants in commonalities call: 

In addition to this issue please provide your feedback on the below issue as well https://github.com/camaraproject/IdentityAndConsentManagement/issues/57 as it would impact the PR 

https://github.com/camaraproject/Commonalities/pull/57

**Comment by eric-murray** [comment]
How are CIBA flows specified within `.well-known/openid-configuration`? Can you give an example.

**Comment by jpengar** [comment]
> How are CIBA flows specified within .well-known/openid-configuration? Can you give an example.

Please refer to https://github.com/camaraproject/IdentityAndConsentManagement/issues/57#issuecomment-1740513326

Further info: https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0.html#registration

**Comment by eric-murray** [comment]
Thanks @jpengar, so it is specified by including an extension grant in `grant_types_supported`. 

Extension grant types are not specified by OAuth2, so this has both advantages (e.g. any grant type could be included there, even ones not invented yet) and a disadvantages (e.g. how would an API client know what might need to be supported without first calling the well-known endpoint? And if multiple grant types are specified, which of those applies to that API?).

When introducing the `.well-known/openid-configuration` requirement into the API specifications, these questions cannot be left hanging. The proposed schema should at least include a description of where the developer should look to answer these specific questions.

**Comment by chrishowell** [comment]
Please bear in mind with the `.well-known` that the caller may not _know_ which CSP's `/well-known` to call to retrieve configuration at the time that the call is created.

**Comment by shilpa-padgaonkar** [comment]
(facepalm) I didnt realise that you didnt commit the suggested change. Hence i directly only viwed the file :/ Will take a look now

**Comment by eric-murray** [comment]
> At the same time, we have to document all of this, and probably add some guidance or references in the APIs to let developers understand the whole process.

My suggestion was to make such guidance part of the boilerplate to be included in the API design guidelines by adding a template `description` to the definition of the security scheme. Otherwise sub-projects will just include minimal definition (this is already happening), which only tells the developer "this API will have security, but you won't find any details here".

If the details will be in a separate document, this document should exist before this security scheme formulation is adopted by APIs.

**Comment by jlurien** [comment]
> > At the same time, we have to document all of this, and probably add some guidance or references in the APIs to let developers understand the whole process.
> 
> My suggestion was to make such guidance part of the boilerplate to be included in the API design guidelines by adding a template `description` to the definition of the security scheme. Otherwise sub-projects will just include minimal definition (this is already happening), which only tells the developer "this API will have security, but you won't find any details here".
> 
> If the details will be in a separate document, this document should exist before this security scheme formulation is adopted by APIs.

I agree. It would be good to have something templated to be included as a section in every info.description, and leave the long explanations to a separate document that may be referenced if needed. Let's work on the details for that.

**Comment by ECORMAC** [comment]
In Number Verification (as Dawid pointed out in #61 above) we have adhered to the use of OIDC security scheme as per communalities guidelines. However OIDC as per standard would also entail the use / delivery of identity tokens.  In our case (Number Verification) we don't see the need for identity tokens (but see the need for Authorization code grant). Is there some recommendation / principle from commonalities that we could use to both adhere to OIDC but not use / implement identity tokens?

**Comment by eric-murray** [comment]
@ECORMAC
Indeed there is no need for the identity token, but this is an issue for the Identity & Consent working group where such decisions are made. Commonalities are only codifying what is decided there within the API design guidelines.

**Comment by ECORMAC** [comment]
Thanks Eric, I'll join the discussion in the Identity & Consent working group.
