### ISSUE TITLE
How to handle termination of subscription in relation to notification API?

### ISSUE THREAD

**Issue by gregory1g** [camaraproject/Commonalities#58]
**Problem description**
In the relation to the common notification API [issues#8](https://github.com/camaraproject/Commonalities/issues/8)
Subscribe/notify API pattern puts API client in a passive role – it has subscribed and expects being notified when something happens (SimSwap for given MSISDN, device leaves a location etc).
However,  the subscriber owning given MSISDN (or a device) can terminate their contract or move to another MNO keeping their MSISDN
MNO must inform API client about this event as well, to allow it to act accordingly.

**Possible evolution**
One can suggest at least 2 approaches to solve this:
Each Camara API is obligated to inform their clients about contract termination using its notification channel (use same end point as it uses for “regular” notifications)
A centralized API to be introduced which an application provider should use to be informed about significant changes related to MSISDNs and devices (contract terminated/suspended/resumed/moved etc)
 
Since a common approach is selected, all Camara APIs must use it.

**Comment by bigludo7** [comment]
Thanks @gregory1g for raising this.

To add a clarification, as of now our pattern follow the first approach mentioned 

> Each Camara API is obligated to inform their clients about contract termination using its notification channel (use same end point as it uses for “regular” notifications)

**Comment by bigludo7** [comment]
@gregory1g As the guidelines was updated (and merged) with above pattern are you fine if I close the issue?

**Comment by gregory1g** [comment]
@bigludo7 , yes.

**Comment by rartych** [comment]
Closing as agreed.
