### ISSUE TITLE
Need for 'Test_definitions' folder under 'code'

### ISSUE THREAD

**Issue by Kevsy** [camaraproject/Commonalities#59]
**Problem description**
There is no directory specified for the test definition(s) associated with API definitions (which do have a directory), meaning the test definition(s) may be hard to find.

**Expected action**
Specify a directory for the test definitions, adding it to the Template Repository. 

**Additional context**
As discussed in #61  , there is a minimum requirement for  a `.feature` file to satisfy the test criteria for API Readiness.

The discussion [includes the point](https://github.com/camaraproject/WorkingGroups/issues/61#issuecomment-1584472138) "Everyone seem to agree that .feature file in main subproject will help with compliance of minimum checklist criteria document."

It seems sensible to place this `.feature` file(s) in a folder under `code`, i.e. `/code/Test_definitions' to make it easier to find.

See [Reference PR](https://github.com/camaraproject/Template_Lead_Repository/pull/1) against the Template Lead Repository

**Comment by rartych** [comment]
I would like to finalize the discussion within the issue in Commonalities and then we can apply changes to Template Lead Repository.

Different Best Practices for Github suggest **/test** folder for hosting test-related files.

Taking into account Fabrizio's view (https://github.com/camaraproject/Template_Lead_Repository/pull/1#issuecomment-1717332724) and current repository structure we can use:
`/code/test/{api_sub_group}/<.feature_files>`
and without API grouping just:
`/code/test/<.feature_files>`

@Kevsy @FabrizioMoggio What do you think?

**Comment by Kevsy** [comment]
Thanks @rartych - LGTM

**Comment by FabrizioMoggio** [comment]
@rartych: it is ok for me, thank you.

**Comment by FabrizioMoggio** [comment]
@Kevsy can we close?

**Comment by Kevsy** [comment]
@FabrizioMoggio We can only close the issue once the [PR](https://github.com/camaraproject/Template_Lead_Repository/pull/1) is merged into Template Lead Repository. I will ask for a CODEOWNER to be allocated to allow the PR merge,

Note, I think the consensus is to use `Test_definitions` 

`/code/Test_defintions/{api_sub_group}/<.feature_files>`
and without API grouping just:
`/code/Test_defintions/<.feature_files>`

...based on the [comment here](https://github.com/camaraproject/Template_Lead_Repository/pull/1#issuecomment-1717332724)

**Comment by rartych** [comment]
@Kevsy @FabrizioMoggio Let's close it during Commonalities call this week.
I prefer the way presented above: https://github.com/camaraproject/Commonalities/issues/59#issuecomment-1721388800

**Comment by rartych** [comment]
Closing as changes introduced to Template Lead Repository.
