### ISSUE TITLE
API Catalogue

### ISSUE THREAD

**Issue by gmuratk** [camaraproject/Commonalities#6]
Inspired by the API Backlog Table, it may be good to have a table format that serves as the catalogue of CAMARA APIs Operations. 

As an example format:

<html>
<body>

API FAMILY | API | version | Operation | Path | Description
-- | -- | -- | -- | -- | --
[QualityOnDemand](https://github.com/camaraproject/QualityOnDemand) | [qod-api.yaml](https://github.com/camaraproject/QualityOnDemand/blob/release-0.8.1/code/API_definitions/qod-api.yaml) | 0.8.1 | POST | /sessions | Create QoS Session to manage latency/throughput priorities
QualityOnDemand | qod-api.yaml | 0.8.1 | GET | /sessions/{sessionId} | Querying for QoS session resource information details
QualityOnDemand | qod-api.yaml | 0.8.1 | DELETE | /sessions/{sessionId} | Deleting a QoS session
QualityOnDemand | qod-api.yaml | 0.8.1 | POST | /notifications |  
DeviceStatus | device-status.yaml | 0.5.0-wip | POST | /roaming | Get the current roaming status and the country information
DeviceLocation | location.yaml | 0.2.0-wip | POST | /verifications | Execute location verification for a user equipment

</body>
</html>

**Comment by shilpa-padgaonkar** [comment]
I have similar concerns regarding the efforts to keep such a table up to date. 
I would not pursue this currently until someone volunteers to take this responsibility :)

**Comment by jordonezlucena** [comment]
I agree with @shilpa-padgaonkar and @hdamker concerns in maintenance. Even API backlog table, which is much simpler, is difficult to keep it updated. 
Even with a (self-nominated) volunteer, I'm not quite sure whether this topic in in scope of Commonalities -- or it is something we should migrate instead to API backlog WG.

**Comment by gmuratk** [comment]
Given the raised concerns around the maintenance of such a list I'll go ahead and close the issue.
