### ISSUE TITLE
Small issues in documentation/*.md files in format and typos.

### ISSUE THREAD

**Issue by dfischer-tech** [camaraproject/Commonalities#65]
**Problem description**
Pls fix the documentation/*.md files in format and typos.

e.g.
Small format adjustments would be appropriate in line:
216 - 218 : change "- - " to "--" or " -"

and typos in lines
70 - "comunicate"
120 - "analyse"
211 - "terminolgy"
217 - "mulitple"
288 - "senstive"
324 - "Unathourized"
405 - "recommendended"
412 - "Referer"
592 - "aAdded"
634 - "ellaborate" and "exisiing" and "errores"
709 - "returnss"
720 - "ascp" - i only know asc for sorting
1010 - "erros"
1050 - "desctiption"
1186 - "Anycase"
1324 - "explicited" (explicitly ?)
1335 - "accross" and "exemple"
1354 - "subscrition"
Thx

**Expected behavior**
format and typos are fixed.

THX

**Comment by rartych** [comment]
@dfischer-tech  Could you prepare PR introducing the needed corrections?
