### ISSUE TITLE
Clarification need for linting response severity 

### ISSUE THREAD

**Issue by Kevsy** [camaraproject/Commonalities#76]
**Problem description**
The linting process in  PR #74  can result in errors/warnings. We should discuss what is the expected outcome for each severity. For example should "warn" result in a change and re-lint, or can it be ignored?

Quoting Herbert's comment from the PR #74 discussion
@[hdamker](https://github.com/hdamker) hdamker [Oct 12, 2023](https://github.com/camaraproject/Commonalities/pull/74#discussion_r1356875964)

Good point. Maybe we can differentiate along the following lines:

    warnings can be ignored when introducing linting first time
        OR (alternative) warnings can be ignored if correcting them would introduce a breaking change
    warnings shall not be introduced with a change (e.g. within a merge, that's the point where linting is done)

**Expected action**
Agree the expected action for errors/warnings for the linring process.

**Additional context**
See #74

**Comment by rartych** [comment]
I propose to close this issue.
The severity of each rule can be modified in [.spectral.yml](https://github.com/camaraproject/Commonalities/blob/main/artifacts/linting_rules/.spectral.yml) file if needed.
The respective guidelines for linting results utilization should be prepared as a part of Release Management process definition.

**Note:** With Megalinter as an umbrella for all dedicated linting tools warnings are ignored: if there is no error then the log is empty. To check for warnings in such case additional workflow can be [started manually](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-linting-Implementation-Guideline.md#manually-running-linting-workflow).

**Comment by rartych** [comment]
We can come back to the issue while extending the ruleset.
