### ISSUE TITLE
Guidelines for operation tags

### ISSUE THREAD

**Issue by rartych** [camaraproject/Commonalities#80]
**Problem description**
Current [API DG ](https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#112-published-routes)says that for each HTTP method (i.e operation) definition should include:

> Tag list to classify methods.

**Expected action**
More detailed guidelines on usage and style of operation tags:

- Definition of tags in a top-level `tags` element
- Adding a tag to each operation

**Additional context**

 `tags` element is **not required** by OAS:

https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#fixed-fields

> A list of tags used by the specification with additional metadata. The order of the tags can be used to reflect on their order by the parsing tools. Not all tags that are used by the [Operation Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#operationObject) must be declared. The tags that are not declared MAY be organized randomly or based on the tools' logic. Each tag name in the list MUST be unique.

The need for guidelines was indicated in the discussion in https://github.com/camaraproject/QualityOnDemand/pull/227

Explanation of tags in [blog post](https://lornajane.net/posts/2019/using-tags-in-your-openapi-spec).

**Comment by eric-murray** [comment]
My view is that tags should be optional for a given API, but if they are used then they should follow a common style.

My preference for the tag style is Title Case.
