### ISSUE TITLE
Commonalities release 0.2.0

### ISSUE THREAD

**Issue by rartych** [camaraproject/Commonalities#81]
**Problem description**
We have introduced changes to API Design Guidelines: mainly related to notifications in CloudEvents format, but also some other updates and corrections. Should we have the next release?

**Expected action**
Agree with TSC on Commonalities release schedule.

Define PRs and Issues that should be closed before the next release.

**Additional context**

**Comment by shilpa-padgaonkar** [comment]
Fully agree. Since the design guidelines included the CloudEvents format, I definitely support this idea to have a new release.

**Comment by rartych** [comment]
In order to finalize changes related to CloudEvents format we need to close:

- PR#43 #43
- PR#83  #83 
and  decide on issues: https://github.com/camaraproject/Commonalities/issues/89 and https://github.com/camaraproject/Commonalities/issues/90

**Comment by rartych** [comment]
I propose to focus on PRs: #43 and #83 as directly related to CloudEvents.
Issue #89 was agreed to be closed and issue #90 extends the Subscription functionality and needs more discussion.
