### ISSUE TITLE
Mandate '+' in all Phone Number formats

### ISSUE THREAD

**Issue by chrishowell** [camaraproject/Commonalities#87]
**Problem description**
The standards are a bit iffy around whether or not a '+' is required for phone numbers, we've agreed in SimSwap to have a '+' only, but I think it makes its sense to make it an agreed CAMARA standard across all APIs.

**Possible evolution**
https://github.com/camaraproject/NumberVerification/issues/65

**Comment by patrice-conil** [comment]
Hi @chrishowell,
I completely agree with you that sharing the same constrained format could simplify the use of the APIs.

**Comment by fernandopradocabrillo** [comment]
HI @chrishowell 
From Telefónica we also agree with this proposal.

**Comment by bigludo7** [comment]
@rartych Asked the question to ...ChatGPT :) if +is mandatory in E.164:

_While the use of the "+" sign is strongly recommended and widely accepted in E.164 format, it is not technically mandatory. E.164 itself does not explicitly require the use of the "+" sign. However, in practice, the use of the "+" sign has become a convention to indicate the international dialing prefix._

So probably we can add a note in Glossary that we mandate the '+' ? WDYT ?

**Comment by fernandopradocabrillo** [comment]
Generally speaking,being explicit with the definition is the best way to avoid misunderstandings and and deviations in implementations. I think we can update the Glossary and apply the definition to every API:

_A public identifier addressing a telephone subscription. In mobile networks it corresponds to the MSISDN (Mobile Station International Subscriber Directory Number). In order to be globally unique it has to be formatted in international format, according to E.164 standard, prefixed with '+'._

**Comment by rartych** [comment]
Referring to  Issue https://github.com/camaraproject/Commonalities/issues/93 : would it be possible to define `format` for phone number string and give recommendation in API Design Guidelines to use it? Glossary is not the main source for CAMARA API requirements.

According to [OAS spec](https://swagger.io/specification/v3/#data-types):
> the `format` property is an open `string`-valued property, and can have any value.

**Comment by nickvenezia** [comment]
A lot of platforms, and databases follow E.164

Interoperability is important.

"DNS Mapping of E.164 numbers
Main article: Telephone number mapping
Some national telephone administrations and telephone companies have implemented an Internet-based database for their numbering spaces. E.164 numbers may be registered in the Domain Name System (DNS) of the Internet in which the second-level domain e164.arpa has been reserved for telephone number mapping (ENUM). In the system, any telephone number may be mapped into a domain name using a reverse sequence of subdomains for each digit. For example, the telephone number +19995550123 translates to the domain name 3.2.1.0.5.5.5.9.9.9.1.e164.arpa. When a number is mapped, a DNS query may be used to locate the service facilities on the Internet that accept and process telephone calls to the owner of record of the number, using, for example, the Session Initiation Protocol (SIP), a call-signaling VoIP protocol whose SIP addresses are similar in format (user@domain...) to e-mail addresses. This allows a direct, end-to-end Internet connection without passing through the public switched telephone network." 
Source: [](https://en.m.wikipedia.org/wiki/E.164)

Additional Links
[https://www.itu.int/rec/T-REC-E.164/]()
[](https://datatracker.ietf.org/doc/html/rfc2806)

**Comment by MarkCornall** [comment]
Can we make a decision on this issue. My proposal is to make the inclusion of "+" mandatory in all cases as a commonality.

**Comment by sachinvodafone** [comment]
I think it's a good idea to let client use phone numbers with or without the '+' sign. This way, both local and international users can enter numbers the way they're comfortable with. I believe, Camara's API will mostly be used by local Opco, for example, a UK client may not prefer to check the device status of Spanish people, so using '+44' may not be useful to them.  So I would prefer to make it optional.

**Comment by MarkCornall** [comment]
Already agreed is e164 that uses country code so "44" in UK would already be mandated. Question is on mandating a "+44" or to leave as is where operators will need to code to handle both +44 and 44 as either can be used. Mandating "+" makes implementation simpler as you only need to support one option.

**Comment by sachinvodafone** [comment]
Thanks for clarifying it @MarkCornall.  However,  mandating the '+' sign, like '+44' for the UK, makes things easier for developer as you stated and I agreed too. However, making it optional like '44' , gives users more choices and can be more friendly for them. So I  would little favour client over developer but I'm open to either option .   Thanks again.

**Comment by rartych** [comment]
PR should be prepared covering Glossary, CAMARA_common.yaml and possibly API Design Guidelines
