### ISSUE TITLE
Notification Subscription - Rules for subscriptionExpireTime behaviour.

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/Commonalities#89]
**Problem description**
Not really a problem but more an clarification In the `POST /subscription`s the `subscriptionExpireTime` is optional.
What is our common understanding if the expire time is not provided?

1. There is no end date (only DELETE operation can terminate the subscription)
2. There is a defaulted period at server hand depending on each implementation
3. The subscription is not time managed and instead occurrence managed - meaning that once the event subscribed occurred, the subscription is terminated

I guess we are more on option 1 (discussed with @jlurien here https://github.com/camaraproject/DeviceLocation/issues/111) but probably worth to add a recommendation in the guideline.

**Possible evolution**

**Alternative solution**

**Additional context**
@rartych perhaps a recommendation  to be added in https://github.com/camaraproject/Commonalities/pull/86 ?

**Comment by PedroDiez** [comment]
Agree with Option 1
There is no end date (only DELETE operation can terminate the subscription)

**Comment by rartych** [comment]
Closed as agreed
