### ISSUE TITLE
Subscription/Notification : adding a maxEventLimit attribute 

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/Commonalities#90]
**Problem description**
As of today the only way to limit a subscriptions is to provide a `subcriptionExpiryTime` and we are not allowing to subscribe to a number of notification. If I need to be notified once that a device entered or existed a zone what is the point to get the subscription valid, when notified, because the subcriptionExpiryTime is not reached ?  (like for sim card that are embedded in equipment that are not suppose to move like in traffic light...).
Request driven from [](https://github.com/camaraproject/DeviceLocation/issues/111)

**Possible evolution**
Add a new attribute in the subscription like `maxEventLimit` (or other better name).

We can position is like this:
If we want to keep the subscription going irrespective of notification count, we can just input the `subcriptionExpiryTime`. An infinite/unlimited number of notifications can be sent as long as the expiry time is not reached and the event keeps happening.
If we both define a `subcriptionExpiryTime` and a `maxEventLimit`,  subscription ends whichever condition is satisfied first.
Similarly, we can create a subscription without a `subcriptionExpiryTime`, only with a `maxEventLimit`. Then, subscription does not expire based on time but terminates if entry/exit event happens n times.
Lastly, it is possible to define neither of those conditions and the subscription goes forever with any number of notifications, unless the user explicitly unsubscribes.
(Thanks to https://github.com/alpaycetin74 proposal)

A new `terminationReason `could be added: `MAX_EVENTS_REACHED`

cc: @jlurien 

**Alternative solution**

**Additional context**

**Comment by jlurien** [comment]
fyi @PedroDiez

**Comment by bigludo7** [comment]
@PedroDiez sure. We have UC for supposed "immobile" device (like for example SIM in traffic light but you can imagine a lot of this kind of device) that get stolen. Our idea in this case is to provide an event when this SIM exit the area where it supposed to work. As this event could occur in one month, 10 years or never... the requirement is to be notified when it's occurred and then the subscription is not anymore necessary. 

You can also imagine for moving piece that you want to be notified when the target place is reached and then don't need anymore the subscription once notified (for example container in a boat reaching a port). 

I think it's better to define clearly in the subscription that you require to be notified n times instead of providing a vague `subcriptionExpiryTime` and having to do a `DELETE`.

Last point: I guess this is something already thought in 3GPP as the monitoring event offers this capability: `https://github.com/camaraproject/Commonalities/issues/90`

**Comment by rartych** [comment]
@bigludo7 - you probably indicated subclause 5.6.0 of 3GPP TS 23.682 which states: 

> Inclusion of either **Maximum Number of Reports** (with a value higher than one) or **Monitoring Duration** makes the
> Monitoring Request a Continuous Monitoring Request. For a Continuous Monitoring Request, a single Monitoring
> Request may generate more than one Monitoring Indication message. Support of continuous monitoring is optional.
> Absence of both Maximum Number of Reports and Monitoring Duration makes the Monitoring Request a **One-time
> Monitoring Request**. For One-time Monitoring Requests, a single Monitoring Request generates only one Monitoring
> Report for an individual UE and for an individual group member UE.
> If for a given Monitoring Event both Maximum Number of Reports and Monitoring Duration are included then the
> monitoring request is considered to expire as soon as one of the conditions is met.

Following this approach impacts also question in https://github.com/camaraproject/Commonalities/issues/89

**Comment by bigludo7** [comment]
> @bigludo7 - you probably indicated subclause 5.6.0 of 3GPP TS 23.682 which states:
> 
> > Inclusion of either **Maximum Number of Reports** (with a value higher than one) or **Monitoring Duration** makes the
> > Monitoring Request a Continuous Monitoring Request. For a Continuous Monitoring Request, a single Monitoring
> > Request may generate more than one Monitoring Indication message. Support of continuous monitoring is optional.
> > Absence of both Maximum Number of Reports and Monitoring Duration makes the Monitoring Request a **One-time
> > Monitoring Request**. For One-time Monitoring Requests, a single Monitoring Request generates only one Monitoring
> > Report for an individual UE and for an individual group member UE.
> > If for a given Monitoring Event both Maximum Number of Reports and Monitoring Duration are included then the
> > monitoring request is considered to expire as soon as one of the conditions is met.
> 
> Following this approach impacts also question in #89

Thanks @rartych 
Yes globally same idea except that not sure we have to be aligned in full detail. 2 points worth to be discussed:

- I'm not sure about enforcing a Maximum Number of Reports strictly superior to 1. Providing 1 should be good.
- If neither provided - The subscription goes forever with any number of notifications, unless the user explicitly unsubscribes. Here we can have a distinct behavior from 3GPP TS 23.682 as we have the /DELETE operation.

**Comment by bigludo7** [comment]
@rartych I propose to wait https://github.com/camaraproject/Commonalities/pull/86 merge and then I will craft a new PR to add a proposal - Works for you?

**Comment by PedroDiez** [comment]
@bigludo7, @rartych Understood the rationale and many thanks for the further explanations & context provided.

Think a reasonable approach would be to model this behavior to be able to set up any value or, in other words, not limiting from the beginning. (*) Considering and bearing in mind that a real Use Case that drives the issue is to control 1 Event from the begining.

(Other Use case that could be possible, when a user enters in roaming several times in a period, the Telco operator considers to inform about Data bundles issued specifically for roaming scenarios) 

To have some alignment with wording already used within Commonalities Notifications section (i.e. _subscriptionExpireTime_), would suggest the term:

_subscriptionMaxEvents_ (optional, integer, minValue 1) (not makes sense to allow value "0")

(*) and allow to provide an exception from API Server in case the value indicated exceeded de business policies in the Telco Operator, so as every operator have flexibility to accomodate their logic based on business needs.

**Comment by bigludo7** [comment]
@PedroDiez Thanks & agreed. `subscriptionMaxEvents` works for me.

**Comment by rkandoi** [comment]
Hello, after some discussion internally at Ericsson, we are not convinced about adding the max events in the subscription request payload. Reasons for this are below:

- A) The use cases highlighted so far all seem to have a "One time event" semantics and no use cases for "n" events have been found.
- B) The "max events" places additional state on the event producer/emitter, i.e., in addition to "subscription expiry", there will be a need to maintain number of events sent and kept consistent, which would be quite hard in the context of a distributed implementation.
- C) It creates application dependencies which may not be fulfilled - Say that an application is expecting 4 events, and the event producer sends the 4 events but the application receives only 3 (for whatever reason one event is lost) and then the application receives a subscription termination event. Or consequently, the application may receive 5 events which is not expected by the application. In this case, the application logic may result in inconsistent state.

Hence, for the reason cited above, we propose to delay the introduction of "max events" feature till it is really needed. However, the "one time events" are reasonable and needed. However to model this (if not as "max events") will require community input.

**Comment by bigludo7** [comment]
Hi @rkandoi 
Thanks for your feedback.

Regarding your last point and point A) we are aligned --> but we need something for one time event. So, if we do not use subscriptionMaxEvents  how do you propose to manage this ?

Regarding point B it's worth to note that this feature is already available in defined 3GPP SCEF/NEF monitoring Event (`maximumNumberOfReports`) and works well as far as i know in our tests. 

Regarding point C this is a relevant point but isn't a point global to the notification? I'm wondering is we shouldn't align with Cloud event https://github.com/cloudevents/spec/blob/main/cloudevents/http-webhook.md#22-delivery-response rules. WDYT ?

Again thanks @rkandoi for your feedback and happy to continue the discussion.

**Comment by rartych** [comment]
Summarizing:

- Currently by default the subscription is created "forever" and the decision on terminating this subscription is in hands of API Consumer - when received expected number of events API Consumer can `DELETE` given subscription. Is it really a pain for developer using the API?

- If the "one-shot" notifications are needed and the `subscriptionMaxEvents` attribute rises questions, then the option may be that  API Design Guideliens can allow subprojects to define additional event types in Subscription Details attribute with special semantics like:
```
      enum:
        - org.camaraproject.geofencing.v0.area-left
        - org.camaraproject.geofencing.v0.area-left-once
```
The suffix  like `-once` indicates that when the event occurs the subscription should be terminated.

**Comment by bigludo7** [comment]
@rartych 
Your first sentence in not completely accurate - we have already `subscriptionExpireTime` to limit (optionally) from start the subscription.

I tend to prefer a dedicated attribute in the subscription to be consistent with `subscriptionExpireTime`.

**Comment by bigludo7** [comment]
Thanks @rkandoi for the proposal and agree on the process ....we probably need some time & more feedback to move forwards.

@rartych I'm fine if you want to close the commonalities PR https://github.com/camaraproject/Commonalities/pull/86 without this feature and we tackle it for next release.

**Comment by sachinvodafone** [comment]
I believe, when users are given the ability to delete their subscription manually after getting the notification they want, it effectively acts like a maxEventLimit. This means that if a user only wants one notification, they can simply opt out (delete the subscription) after getting the first one.
The concept of "maxEventLimit" is particularly looks relevant where delete the subscriptions explicitly may be either impractical or not preferred. However, this method might introduce additional complexity in the system's design that team already highlighted in this discussion.

**Comment by hdamker** [comment]
> you probably indicated subclause 5.6.0 of 3GPP TS 23.682 which states

Looking on the definition from 3GPP which Rafal cited above, i liked the following: 

> "Absence of both Maximum Number of Reports and Monitoring Duration makes the Monitoring Request a One-time
Monitoring Request"

I haven't followed all discussion, but have you yet defined what the semantic of a subscription without expiryTime is? Could it be defined as a One-time delivery?

Beyond that I agree that a feature "maxEventLimit" with n>1 need to be first have an use case before the complexity on implementation side is added.

**Comment by bigludo7** [comment]
Refreshing this discussion in order to make some progress  (cc @shilpa-padgaonkar )

My understanding is while the UC is globally shared we did not have an agreement on the solution. I saw mainly 3 options here

1. Specify in the event type name the request behavior (post from @rartych  - the event will be `org.camaraproject.geofencing.v0.area-left-once`)
2. Specify that if expiryTime is not defined then it's an one-time revent (as suggested by @hdamker )
3. Add another field in the subscription to specify the behavior - here we have 2 proposals:

   - 3.1 add a 'recurrenceType' attribue that specify this behaviour (see @rkandoi proposal)
   - .3.2 add a `subscriptionMaxEvents`  as in 3GPP (initial proposal and attribute name defined by @PedroDiez)

In order to move forward, may I suggest people/company involved in this discussion to answer following questions:

1. Do you share this requirement to limit notification occurrence at least to 1?
2. What proposal is fine/blocking from you ?

Speaking for Orange:

1. Yes
2. Preference for 3.2 with `subscriptionMaxEvents` but OK for 3.1. We can live with proposal 1. Proposal 2 is no go for us as it is confusing with `DELETE` operation behavior.

Thanks for you help to get some progress.

**Comment by shilpa-padgaonkar** [comment]
@bigludo7 : Thanks Ludovic for consolidating the comments. I would prefer 3.1 or 3.2. 

Just as FYI, the current wip document on subscriptions in CloudEvents suggests adding such attributes under a subscription's config (A set of key/value pairs that modify the configuration of the subscription related to the event generation process.)

Even if this doc is WIP, the proposal (3.1, 3.2) are closer to this idea.

**Comment by nickvenezia** [comment]
The API family for Consent and Measurement would benefit from the introduction of a 'maxEventLimit' feature, especially in situations where the number of events ('N') is greater than one. To illustrate, imagine managing a chain of Ford dealerships and seeking to evaluate the effectiveness of online advertising. 

In this scenario, tracking 'Location Visits' becomes a crucial metric. For instance, if I set a 'conversion event window' of 60 days, it's possible that during this time, 580 distinct individuals see the advertisement AND subsequently visit the dealership. These visits could total 2700, indicating that some visitors are returning multiple times. 

As an advertiser, I am particularly interested in these repeat visitors. After their first visit to the dealership, it would be advantageous to tailor the advertising content for them, perhaps by emphasizing additional features of the cars or offering attractive financing options. 

This is because their repeated visits imply a stronger interest in the product.

Hope this helps @bigludo7 for a use case.

**Comment by PedroDiez** [comment]
From Telefónica:
1. No problem to focus firstly in 1 occurrence case
2. Preference for 3.2 with `subscriptionMaxEvents`, as we think is more flexible to deal with generic N occurrence in future

**Comment by bigludo7** [comment]
@shilpa-padgaonkar @nickvenezia @PedroDiez Thanks for your feedbacks !
As we converging to 3.2 I will next week propose a PR for this... except if we got here some strong opinion against.

**Comment by rkandoi** [comment]
I am still not sure if we are making the right choices but I don't have any good answers. So if you think subscriptionMaxEvents is the way to go - then okay.

But,
- I tried looking at the Identity and Consent APIs and did not find any documentation related to the use case @nickvenezia mentioned. Could you please share a link?

- How are you thinking that the following scenarios should be handled. In my opinion, some of these are important to be addressed before taking a decision:

    -   The API is designed to send only one event / notification and then the stream ends, but the subscription request has maxEvents set to 10. Should the API Request to create the subscription fail or what would be your suggestion?
    - Are there any server-side guarantees associated with maxEvents, i.e., 
        - how should application developers / clients behave when maxEvents is large, i.e. a subscription termination event is received prematurely? 
        - how should application developers / clients behave when maxEvents is smaller (i.e., more than the expected number of events are received) before the termination event?

cc: @bigludo7

**Comment by sachinvodafone** [comment]
from Vodafone’s prospective ,

1. Yes
 **option1**  can lead to a proliferation of event types, making the system more complex and will become crowded with numerous variations. For example, for every existing event type, a new event type needs to be created to accommodate variations like "left-once," it would result in an increase in the number of event types. In this scenario, the number of event types would double for each new option


**Option 2**  could potentially limit the flexibility for users who might want to set up subscriptions without a predefined expiration time, indicating an unlimited or indefinite subscription. The absence of a subscription time in this option implies a one-time event, which may not align with the user's intention of keeping the subscription active until they decide to delete it.


**Option 3.2** seems like a sensible choice as it is already used by a widely recognised standard like 3GPP. Though current use cases don't demand 'N' events as per above discussion, however having a scalable design can help accommodate potential needs without requiring significant modifications to the system.

**Comment by bigludo7** [comment]
Thanks all for your valuable feedback. I will propose a PR to move forward.

Regarding @rkandoi points:

> Assume an API is designed to send only one event / notification and then the stream ends, but the subscription request has maxEvents set to 10. Should the API Request to create the subscription fail or what would be your suggestion?

In any case the server side has always the possibility to terminate a subscription. What is important is the server side to send the "subscription-ends" notification to inform the consumer side. So regarding the UC you mentioned, I expect the server to create the subscription and then terminates it when the event occurred. Note: I'm not sure we have as of now UC as you described here.

> Are there any server-side guarantees associated with maxEvents, i.e.,
how should application developers / clients behave when maxEvents is large, i.e. a subscription termination event is received prematurely?
how should application developers / clients behave when maxEvents is smaller (i.e., more than the expected number of events are received) before the termination event?

For the fist case, I guess the "subscription-ends" notification should also be useful. Nothing prevent also the server at subscription time to refuse a subscription request if the maxEvents is too high.
For the second I'm not sure to get it. When the maxEvents is reach, subscriptions ends, and the subscription-ends" notification is sent. Note: the subscription-ends" event is not counted in the maxEvents.
