### ISSUE TITLE
Test definitions - implementations guidelines and artifacts

### ISSUE THREAD

**Issue by rartych** [camaraproject/Commonalities#94]
**Problem description**
Delivery of  **API test cases and documentation** is one of criteria in API Readiness Checklist.
Each subproject needs to develop a Gherkin feature file for specified API.
_If subprojects also intend to add test implementations, an aligned single implementation that is agreed amongst all provider implementors could be added to the main subproject repo._

**Possible evolution**
Definition of common guidelines and artifacts that would simplify development of test definition, documentation and implementation based on current experience in subprojects and within participating organizations.

**Additional context**
As listed in https://github.com/camaraproject/SimSwap/issues/63  following projects  already provide Gherkin feature files:

- [EdgeCloud (Traffic Influence)](https://github.com/camaraproject/EdgeCloud/blob/main/code/Test_definitions/Traffic_Influence_Test.feature)
 -  [QualityOnDemand](https://github.com/camaraproject/QualityOnDemand/blob/main/code/cucumber/src/test/resources/feature/QoD_API_Test.feature)
   - [HomeDevicesQoD](https://github.com/camaraproject/HomeDevicesQoD/blob/main/code/Test_definitions/home_devices_qod_setQos.feature)

**Comment by bigludo7** [comment]
Hello @rartych and team,
How we can move forward on this? as I assume this is the only missing point in a lot of APIs to reach completion.

Looking in details of the Test Case already contributed and seems we are not far from one WG to another - need few alignements.

- There is a lot similarities between https://github.com/camaraproject/HomeDevicesQoD/blob/main/code/Test_definitions/home_devices_qod_setQos.feature , https://github.com/camaraproject/SimSwap/pull/68 (provided by GSMA) and https://github.com/camaraproject/DeviceLocation/pull/119. The difference are very little (use of first person or third person, payload provided or described). 
- The Test Case file in QoD (https://github.com/camaraproject/QualityOnDemand/blob/main/code/cucumber/src/test/resources/feature/QoD_API_Test.feature) is slightly different as it's a bit light on the 'when' description and for one scenario can have several when/then
-The one for traffic influence is very detailed (same grammar) and also feature several when/then for a scenario -  https://github.com/camaraproject/EdgeCloud/blob/main/code/Test_definitions/Traffic_Influence_Test.feature
- The file provided by Telefonica in SimSwap (https://github.com/camaraproject/SimSwap/pull/70) is close but use a specific clause [context] that probably we should avoid?

We need to agree on:
- Having one feature file per API or Resource ? or we keep this flexible and it's up to each project to manage this? (I prefer this later)
- probably good for consistency to use all same pronoun (I or impersonal) 
- Scenario identifier. To trigger the discussion I propose '@'<(mandatory)name of the resource>_<(mandatory)number XX>_<(optional)short detail> (like `@check_simswap_01_Verify_Swap_True_Default_MaxAge`)
- Do we agree to have several when/then in one scenario ?
- Providing either API literal request value (with exemple) or payload 'ready to use' (as in home device QoD) is fine?
- ...

Definitely looking for consumer of these file to get their perspective. The less they have to do to use these files the better it will be.

**Comment by bigludo7** [comment]
Thanks @mdomale for your comments and the url sources which are very helpful

To sump-up:

- Proposal is to manage **single feature file** (Having multiple feature inside single feature file is unattainable)
- **Third Person pronoun is advisable** as using the third person, particularly in English, conveys information in a more official and impartial manner 
- about scenario identifier, following your recommendation it should be  '@'<(mandatory)name of the resource>
**-**<(mandatory)number XX>**-**<(optional)short detail i**n lower case and using - separator**> (like `@check_simswap-01-verify-swap-true-default-maxAge`) - As we use '_' in resource using then "-" could be confusing - WDYT?
- I'm not sure we can enforce any rule about using only one Given, When and Then keywords in one flow of a scenario but got your point to provide this a a recommendation.

Expecting also comments from others companies involved in day to day CAMARA APIs crafting :)

**Comment by shilpa-padgaonkar** [comment]
Thanks @mdomale and @bigludo7 for your inputs and feedback. While we wait for few more days to get more feedback on the inputs, I would also propose to create a short Camara-API-Testing-Guidelines.md doc with the below content:

- Short intro about the API test cases requirements specified in https://github.com/camaraproject/Commonalities/blob/main/documentation/API-Readiness-Checklist.md
- Location of the feature file in our subproject repos
- Best practices and recommendations section, which will incorporate all the above specified inputs

With this doc in place, we would not need to search for old issues regarding these discussed points when needed later, and would also allow the new Camara members to get an overview on the topic.

**Comment by jlurien** [comment]
Answering also to @bigludo7's questions. I think we are quite aligned with previous responses:

- Having one feature file per API or Resource ? or we keep this flexible and it's up to each project to manage this? (I prefer this later)

We also prefer one feature file per operationId.

- probably good for consistency to use all same pronoun (I or impersonal)

Yes, we should agree on a common wording. The simpler the better.

As a example, to be refined:

```
Background: (assuming one feature file per operationId)
  Given:
    the environment 
    the path "path"
    the method "method"

Given:
  the (path param|query param|header) "name" is set to "value"
  the request body is set to
    """
    """
When:
  a "operationId" request is sent

Then:
  the status code is "X"
  the response value at "JSON-path" is "value"
```

- Scenario identifier. To trigger the discussion I propose '@'<(mandatory)name of the resource><
(mandatory)number XX><(optional)short detail> (like @check_simswap_01_Verify_Swap_True_Default_MaxAge)

We think it's good to include the operationId of the endpoint, along with some number to allow unique identification, and some description may also help, so a proposal could be:

@<operationId>.<uniqueIdinteger>[.<optional_short_description>]
(separator here could be other than "." but we should choose one that cannot be part of the components)

- Do we agree to have several when/then in one scenario ?

It is preferable to have simple scenarios with just 1 when. While testing APIs, the structure is usually:

Given: request setup
When: request is sent
Then: response is validated

If some complex scenario requires that filling a request depends on the response from a previous one, we may allow several `when`  

- Providing either API literal request value (with exemple) or payload 'ready to use' (as in home device QoD) is fine?

For the `Given` steps, in some cases we may give exact values for some parameters, for example providing wrong values to provoke an error, while in other cases the exact value cannot be known in advance and we have to ask the tester to fill the value. For example, in location-verification we should ask the tester to provide the well known latitude, longitude of a device to test a verificationResult=true scenario.
