### ISSUE TITLE
Filtering - parameters support

### ISSUE THREAD

**Issue by gmuratk** [camaraproject/Commonalities#98]
**Problem description**
Section 8.3 Filtering of Design Guideline should have a clear statement that not all parameters should be supported for Filtering.

**Expected action**
Add clarification in section 8.3 Filtering that not every parameter should be supported for filtering.

**Additional context**
N/A

**Comment by rartych** [comment]
Please look at Issue https://github.com/camaraproject/Commonalities/issues/10 and the corresponding [PR#82](https://github.com/camaraproject/Commonalities/pull/82).

**Comment by shilpa-padgaonkar** [comment]
@rartych If I understood the request correctly, it's more about making it explicit in the design guidelines that not all parameters must be subjected to filtering and sorting.

**Comment by gmuratk** [comment]
DG was updated with additional statements as suggested.
